// Generated by `wrangler types` — run `pnpm cf-typegen` to regenerate from
// wrangler.toml. This committed stub lets `tsc` pass before the first codegen;
// the typed binding env lands here once you add bindings + run cf-typegen.
