#!/usr/bin/env node
/**
 * guard.mjs — PreToolUse enforcement: the DETERMINISTIC layer under the advisory
 * NEVERs in CLAUDE.md. It runs before every Edit / Write / MultiEdit and blocks
 * the write when the target is a protected path (exit 2 = block, the stderr note
 * is shown to the agent; exit 0 = allow).
 *
 * Committed + wired in .claude/settings.json, so the guardrail ships with the
 * template — a client clone, a teammate, and CI all get it (a Skill/rule is
 * advisory; a hook is guaranteed).
 *
 * Protected:
 *  1. GENERATED design-token files (clobbered by `pnpm tokens:build`).
 *  2. shadcn CLI-managed primitives (`@indiecrafts/packages-web-ui`).
 *  3. Real `.env*` files (only `.env.example` is tracked).
 *  4. A secret leaked under a `NEXT_PUBLIC_` prefix (code files only).
 */
import { readFileSync } from "node:fs";

let payload = {};
try {
  payload = JSON.parse(readFileSync(0, "utf8") || "{}");
} catch {
  process.exit(0); // never let a parse error block a legitimate edit
}

const input = payload.tool_input || {};
const file = input.file_path || "";
if (!file) process.exit(0);
const norm = file.replace(/\\/g, "/");

// Text being written: Write.content, Edit.new_string, MultiEdit.edits[].new_string.
const added = [
  input.content,
  input.new_string,
  ...(Array.isArray(input.edits)
    ? input.edits.map((e) => e && e.new_string)
    : []),
]
  .filter(Boolean)
  .join("\n");

function block(msg) {
  process.stderr.write(`✗ guard: ${msg}\n`);
  process.exit(2);
}

// 1. Generated design-token files — regenerated by `pnpm tokens:build`; hand-edits vanish.
if (/\/ui-tokens\/src\/(generated\/|native\/tokens\.ts$)/.test(norm)) {
  block(
    `${file} is GENERATED by \`pnpm tokens:build\` — a hand-edit is lost on the next build.\n` +
      `  Edit the source of truth (code/packages/shared/ui-tokens/src/shared/tokens.json), then run \`pnpm tokens:build\`.`,
  );
}

// 2. shadcn CLI-managed primitives — never hand-edit. A colocated `*.tokens.json`
//    sidecar is the exception: `shadcn add` never emits one, it never touches the
//    .tsx, and `pnpm tokens:build` globs it by design — so it is not a primitive edit.
if (
  /\/packages\/web\/ui\/src\/web\//.test(norm) &&
  !/\.tokens\.json$/.test(norm)
) {
  block(
    `${file} is a shadcn CLI-managed primitive (@indiecrafts/packages-web-ui) — don't hand-edit.\n` +
      `  Re-add via the shadcn CLI, or compose/wrap it in src/user-interface/ instead.`,
  );
}

// 3. Real .env files — only .env.example is tracked.
if (/(^|\/)\.env(\.[^/]*)?$/.test(norm) && !/\.env\.example$/.test(norm)) {
  block(
    `Never write a real .env file — it holds secrets and must not be tracked.\n` +
      `  Only .env.example is committed; put real values in your shell or the platform env.`,
  );
}

// 4. Secret under a NEXT_PUBLIC_ prefix — bundled to the browser. Code files only
//    (docs legitimately quote the anti-pattern, so skip .md/.mdx).
if (!/\.mdx?$/.test(norm)) {
  const matches =
    added.match(
      /NEXT_PUBLIC_[A-Z0-9_]*(TOKEN|SECRET|KEY|PASSWORD|PRIVATE)\b/g,
    ) || [];
  // A *publishable* key is public by design (Clerk / Stripe `pk_…` — the SDK reads
  // it in the browser). It is not a secret, so it is allowed under NEXT_PUBLIC_.
  // Every real secret (SECRET / TOKEN / PRIVATE / PASSWORD / other KEY) still blocks.
  const leak = matches.find((m) => !/PUBLISHABLE/.test(m));
  if (leak) {
    block(
      `${leak} — a secret under NEXT_PUBLIC_ is inlined into the client bundle.\n` +
        `  Drop the NEXT_PUBLIC_ prefix so it stays server-only (config NEVERs).`,
    );
  }
}

process.exit(0);
