// AUTO-GENERATED by scripts/generate-i18n-registry.mjs
// DO NOT EDIT — run `pnpm gen:i18n` to regenerate. Drift caught by `pnpm verify:i18n`.

import _3dPinEn from "../components/ui-effects/3d-pin.en.json";
import about1En from "../components/pages-marketing/about-1/en.json";
import animatedTestimonialsEn from "../components/ui-effects/AnimatedTestimonials/en.json";
import appSidebarEn from "../components/layouts/DashboardLayout/sidebars/AppSidebar/en.json";
import chartAreaAxesEn from "../components/sections-app-charts/ChartAreaAxes/en.json";
import chartAreaDefaultEn from "../components/sections-app-charts/ChartAreaDefault/en.json";
import chartAreaGradientEn from "../components/sections-app-charts/ChartAreaGradient/en.json";
import chartAreaIconsEn from "../components/sections-app-charts/ChartAreaIcons/en.json";
import chartAreaInteractiveEn from "../components/sections-app-charts/ChartAreaInteractive/en.json";
import chartAreaLegendEn from "../components/sections-app-charts/ChartAreaLegend/en.json";
import chartAreaLinearEn from "../components/sections-app-charts/ChartAreaLinear/en.json";
import chartAreaStackedEn from "../components/sections-app-charts/ChartAreaStacked/en.json";
import chartAreaStackedExpandEn from "../components/sections-app-charts/ChartAreaStackedExpand/en.json";
import chartAreaStepEn from "../components/sections-app-charts/ChartAreaStep/en.json";
import chartBarActiveEn from "../components/sections-app-charts/ChartBarActive/en.json";
import chartBarDefaultEn from "../components/sections-app-charts/ChartBarDefault/en.json";
import chartBarHorizontalEn from "../components/sections-app-charts/ChartBarHorizontal/en.json";
import chartBarInteractiveEn from "../components/sections-app-charts/ChartBarInteractive/en.json";
import chartBarLabelCustomEn from "../components/sections-app-charts/ChartBarLabelCustom/en.json";
import commandPaletteEn from "../components/ui-effects/CommandPalette/en.json";
import contact1En from "../components/sections-marketing-contact/contact-1/en.json";
import content1En from "../components/sections-marketing-content/content-1/en.json";
import content2En from "../components/sections-marketing-content/content-2/en.json";
import content3En from "../components/sections-marketing-content/content-3/en.json";
import content4En from "../components/sections-marketing-content/content-4/en.json";
import content5En from "../components/sections-marketing-content/content-5/en.json";
import content6En from "../components/sections-marketing-content/content-6/en.json";
import content7En from "../components/sections-marketing-content/content-7/en.json";
import cta1En from "../components/sections-marketing-cta/cta-1/en.json";
import dashboard1En from "../components/pages-app/dashboard-1/en.json";
import dashboardHeaderEn from "../components/layouts/DashboardLayout/DashboardHeader/en.json";
import dataTableEn from "../components/sections-app-data/DataTable/en.json";
import ditherShaderEn from "../components/ui-effects/DitherShader/en.json";
import error1En from "../components/pages-error/error-1/en.json";
import faq1En from "../components/sections-marketing-faq/faq-1/en.json";
import faq2En from "../components/sections-marketing-faq/faq-2/en.json";
import faq3En from "../components/sections-marketing-faq/faq-3/en.json";
import faq4En from "../components/sections-marketing-faq/faq-4/en.json";
import features1En from "../components/sections-marketing-features/features-1/en.json";
import features10En from "../components/sections-marketing-features/features-10/en.json";
import features11En from "../components/sections-marketing-features/features-11/en.json";
import features12En from "../components/sections-marketing-features/features-12/en.json";
import features2En from "../components/sections-marketing-features/features-2/en.json";
import features3En from "../components/sections-marketing-features/features-3/en.json";
import features4En from "../components/sections-marketing-features/features-4/en.json";
import features5En from "../components/sections-marketing-features/features-5/en.json";
import features6En from "../components/sections-marketing-features/features-6/en.json";
import features7En from "../components/sections-marketing-features/features-7/en.json";
import features8En from "../components/sections-marketing-features/features-8/en.json";
import features9En from "../components/sections-marketing-features/features-9/en.json";
import footer1En from "../components/sections-marketing-footer/footer-1/en.json";
import forgotPasswordEn from "../components/sections-auth/ForgotPassword/en.json";
import forgotPassword1En from "../components/pages-auth/forgot-password-1/en.json";
import heroVideoDialogEn from "../components/ui-effects/HeroVideoDialog/en.json";
import iconCloudEn from "../components/ui-effects/IconCloud/en.json";
import landing1En from "../components/pages-marketing/landing-1/en.json";
import layoutTextFlipEn from "../components/ui-effects/LayoutTextFlip/en.json";
import localeSwitcherEn from "../components/layouts/_shared/LocaleSwitcher/en.json";
import login1En from "../components/pages-auth/login-1/en.json";
import loginFormEn from "../components/sections-auth/LoginForm/en.json";
import loginPageEn from "../components/sections-auth/Login/en.json";
import navActionsEn from "../components/layouts/DashboardLayout/nav/NavActions/en.json";
import navDocumentsEn from "../components/layouts/DashboardLayout/nav/NavDocuments/en.json";
import navFavoritesEn from "../components/layouts/DashboardLayout/nav/NavFavorites/en.json";
import navMainEn from "../components/layouts/DashboardLayout/nav/NavMain/en.json";
import navProjectsEn from "../components/layouts/DashboardLayout/nav/NavProjects/en.json";
import navUserEn from "../components/layouts/DashboardLayout/nav/NavUser/en.json";
import navWorkspacesEn from "../components/layouts/DashboardLayout/nav/NavWorkspaces/en.json";
import notFound1En from "../components/pages-error/not-found-1/en.json";
import pixelatedCanvasEn from "../components/ui-effects/PixelatedCanvas/en.json";
import pricing1En from "../components/sections-marketing-pricing/pricing-1/en.json";
import pricingComparatorEn from "../components/sections-marketing-pricing/pricing-comparator/en.json";
import searchFormEn from "../components/layouts/DashboardLayout/widgets/SearchForm/en.json";
import sectionCardsEn from "../components/sections-app-dashboard/SectionCards/en.json";
import settingsDialogEn from "../components/sections-app-settings/SettingsDialog/en.json";
import sidebarEn from "../components/layouts/SidebarLayout/en.json";
import sidebarLeftEn from "../components/layouts/DashboardLayout/sidebars/SidebarLeft/en.json";
import sidebarOptInFormEn from "../components/layouts/DashboardLayout/widgets/SidebarOptInForm/en.json";
import sidebarRightEn from "../components/layouts/DashboardLayout/sidebars/SidebarRight/en.json";
import sidebarTriggerEn from "../components/ui-effects/SidebarTrigger/en.json";
import signup1En from "../components/pages-auth/signup-1/en.json";
import signupFormEn from "../components/sections-auth/SignupForm/en.json";
import signupPageEn from "../components/sections-auth/SignUp/en.json";
import siteFooterEn from "../components/layouts/DefaultLayout/SiteFooter/en.json";
import siteHeaderEn from "../components/layouts/DefaultLayout/SiteHeader/en.json";
import skipLinkEn from "../components/layouts/_shared/SkipLink/en.json";
import stats1En from "../components/sections-marketing-stats/stats-1/en.json";
import stats2En from "../components/sections-marketing-stats/stats-2/en.json";
import stats3En from "../components/sections-marketing-stats/stats-3/en.json";
import stats4En from "../components/sections-marketing-stats/stats-4/en.json";
import team1En from "../components/sections-marketing-team/team-1/en.json";
import teamSwitcherEn from "../components/layouts/DashboardLayout/widgets/TeamSwitcher/en.json";
import testimonials1En from "../components/sections-marketing-testimonials/testimonials-1/en.json";
import themeToggleEn from "../components/layouts/_shared/ThemeToggle/en.json";
import tweetNotFoundEn from "../components/ui-effects/TweetNotFound/en.json";
import versionSwitcherEn from "../components/layouts/DashboardLayout/widgets/VersionSwitcher/en.json";
import webcamPixelGridEn from "../components/ui-effects/WebcamPixelGrid/en.json";
import worldMapEn from "../components/ui-effects/WorldMap/en.json";

const BLOCK_MESSAGES: Record<string, Record<string, unknown>> = {
  "3d-pin": _3dPinEn,
  "about-1": about1En,
  "animated-testimonials": animatedTestimonialsEn,
  "app-sidebar": appSidebarEn,
  "chart-area-axes": chartAreaAxesEn,
  "chart-area-default": chartAreaDefaultEn,
  "chart-area-gradient": chartAreaGradientEn,
  "chart-area-icons": chartAreaIconsEn,
  "chart-area-interactive": chartAreaInteractiveEn,
  "chart-area-legend": chartAreaLegendEn,
  "chart-area-linear": chartAreaLinearEn,
  "chart-area-stacked": chartAreaStackedEn,
  "chart-area-stacked-expand": chartAreaStackedExpandEn,
  "chart-area-step": chartAreaStepEn,
  "chart-bar-active": chartBarActiveEn,
  "chart-bar-default": chartBarDefaultEn,
  "chart-bar-horizontal": chartBarHorizontalEn,
  "chart-bar-interactive": chartBarInteractiveEn,
  "chart-bar-label-custom": chartBarLabelCustomEn,
  "command-palette": commandPaletteEn,
  "contact-1": contact1En,
  "content-1": content1En,
  "content-2": content2En,
  "content-3": content3En,
  "content-4": content4En,
  "content-5": content5En,
  "content-6": content6En,
  "content-7": content7En,
  "cta-1": cta1En,
  "dashboard-1": dashboard1En,
  "dashboard-header": dashboardHeaderEn,
  "data-table": dataTableEn,
  "dither-shader": ditherShaderEn,
  "error-1": error1En,
  "faq-1": faq1En,
  "faq-2": faq2En,
  "faq-3": faq3En,
  "faq-4": faq4En,
  "features-1": features1En,
  "features-10": features10En,
  "features-11": features11En,
  "features-12": features12En,
  "features-2": features2En,
  "features-3": features3En,
  "features-4": features4En,
  "features-5": features5En,
  "features-6": features6En,
  "features-7": features7En,
  "features-8": features8En,
  "features-9": features9En,
  "footer-1": footer1En,
  "forgot-password": forgotPasswordEn,
  "forgot-password-1": forgotPassword1En,
  "hero-video-dialog": heroVideoDialogEn,
  "icon-cloud": iconCloudEn,
  "landing-1": landing1En,
  "layout-text-flip": layoutTextFlipEn,
  "locale-switcher": localeSwitcherEn,
  "login-1": login1En,
  "login-form": loginFormEn,
  "login-page": loginPageEn,
  "nav-actions": navActionsEn,
  "nav-documents": navDocumentsEn,
  "nav-favorites": navFavoritesEn,
  "nav-main": navMainEn,
  "nav-projects": navProjectsEn,
  "nav-user": navUserEn,
  "nav-workspaces": navWorkspacesEn,
  "not-found-1": notFound1En,
  "pixelated-canvas": pixelatedCanvasEn,
  "pricing-1": pricing1En,
  "pricing-comparator": pricingComparatorEn,
  "search-form": searchFormEn,
  "section-cards": sectionCardsEn,
  "settings-dialog": settingsDialogEn,
  "sidebar": sidebarEn,
  "sidebar-left": sidebarLeftEn,
  "sidebar-opt-in-form": sidebarOptInFormEn,
  "sidebar-right": sidebarRightEn,
  "sidebar-trigger": sidebarTriggerEn,
  "signup-1": signup1En,
  "signup-form": signupFormEn,
  "signup-page": signupPageEn,
  "site-footer": siteFooterEn,
  "site-header": siteHeaderEn,
  "skip-link": skipLinkEn,
  "stats-1": stats1En,
  "stats-2": stats2En,
  "stats-3": stats3En,
  "stats-4": stats4En,
  "team-1": team1En,
  "team-switcher": teamSwitcherEn,
  "testimonials-1": testimonials1En,
  "theme-toggle": themeToggleEn,
  "tweet-not-found": tweetNotFoundEn,
  "version-switcher": versionSwitcherEn,
  "webcam-pixel-grid": webcamPixelGridEn,
  "world-map": worldMapEn,
};

/**
 * Returns `{ "<block-key>": {...}, ... }` merged as-is. Non-English
 * locales fall back to the English sample — clients fill in real
 * translations per page when they customize.
 */
export function loadBlockMessages(): Record<string, unknown> {
  return { ...BLOCK_MESSAGES };
}
