// AUTO-GENERATED by scripts/generate-i18n-registry.mjs
// DO NOT EDIT — run `pnpm gen:i18n` to regenerate. Drift caught by `pnpm verify:i18n`.

import _3dPinEn from "../components/ui-effects/3d-pin.en.json";
import about01En from "../components/pages-about/about-01/en.json";
import about02En from "../components/pages-about/about-02/en.json";
import ai01En from "../components/sections-ai/ai-01/en.json";
import ai02En from "../components/sections-ai/ai-02/en.json";
import ai03En from "../components/sections-ai/ai-03/en.json";
import ai04En from "../components/sections-ai/ai-04/en.json";
import ai05En from "../components/sections-ai/ai-05/en.json";
import animatedTestimonialsEn from "../components/ui-effects/animated-testimonials/en.json";
import bento1En from "../components/sections-bento/bento-1/en.json";
import bento10En from "../components/sections-bento/bento-10/en.json";
import bento11En from "../components/sections-bento/bento-11/en.json";
import bento12En from "../components/sections-bento/bento-12/en.json";
import bento13En from "../components/sections-bento/bento-13/en.json";
import bento14En from "../components/sections-bento/bento-14/en.json";
import bento2En from "../components/sections-bento/bento-2/en.json";
import bento3En from "../components/sections-bento/bento-3/en.json";
import bento4En from "../components/sections-bento/bento-4/en.json";
import bento5En from "../components/sections-bento/bento-5/en.json";
import bento6En from "../components/sections-bento/bento-6/en.json";
import bento7En from "../components/sections-bento/bento-7/en.json";
import bento8En from "../components/sections-bento/bento-8/en.json";
import bento9En from "../components/sections-bento/bento-9/en.json";
import brand01En from "../components/pages-brand/brand-01/en.json";
import chartAreaAxesEn from "../components/ui-molecules/chart/area/axes/en.json";
import chartAreaDefaultEn from "../components/ui-molecules/chart/area/default/en.json";
import chartAreaGradientEn from "../components/ui-molecules/chart/area/gradient/en.json";
import chartAreaIconsEn from "../components/ui-molecules/chart/area/icons/en.json";
import chartAreaInteractiveEn from "../components/ui-molecules/chart/area/interactive/en.json";
import chartAreaLegendEn from "../components/ui-molecules/chart/area/legend/en.json";
import chartAreaLinearEn from "../components/ui-molecules/chart/area/linear/en.json";
import chartAreaStackedEn from "../components/ui-molecules/chart/area/stacked/en.json";
import chartAreaStackedExpandEn from "../components/ui-molecules/chart/area/stacked-expand/en.json";
import chartAreaStepEn from "../components/ui-molecules/chart/area/step/en.json";
import chartBarActiveEn from "../components/ui-molecules/chart/bar/active/en.json";
import chartBarDefaultEn from "../components/ui-molecules/chart/bar/default/en.json";
import chartBarHorizontalEn from "../components/ui-molecules/chart/bar/horizontal/en.json";
import chartBarInteractiveEn from "../components/ui-molecules/chart/bar/interactive/en.json";
import chartBarLabelCustomEn from "../components/ui-molecules/chart/bar/label-custom/en.json";
import codeDemo1En from "../components/sections-code-demo/code-demo-1/en.json";
import codeDemo2En from "../components/sections-code-demo/code-demo-2/en.json";
import codeDemo3En from "../components/sections-code-demo/code-demo-3/en.json";
import codeDemo4En from "../components/sections-code-demo/code-demo-4/en.json";
import commandMenu01En from "../components/ui-molecules/command-menu/01/en.json";
import commandMenu02En from "../components/ui-molecules/command-menu/02/en.json";
import commandMenu03En from "../components/ui-molecules/command-menu/03/en.json";
import commandPaletteEn from "../components/ui-effects/command-palette/en.json";
import contact01En from "../components/sections-contact/contact-01/en.json";
import contactPage01En from "../components/pages-contact/contact-page-01/en.json";
import contactPage02En from "../components/pages-contact/contact-page-02/en.json";
import contactPage03En from "../components/pages-contact/contact-page-03/en.json";
import contactPage04En from "../components/pages-contact/contact-page-04/en.json";
import contactPage05En from "../components/pages-contact/contact-page-05/en.json";
import contactPage06En from "../components/pages-contact/contact-page-06/en.json";
import content01En from "../components/sections-content/content-01/en.json";
import content02En from "../components/sections-content/content-02/en.json";
import content03En from "../components/sections-content/content-03/en.json";
import content04En from "../components/sections-content/content-04/en.json";
import content05En from "../components/sections-content/content-05/en.json";
import content06En from "../components/sections-content/content-06/en.json";
import content07En from "../components/sections-content/content-07/en.json";
import content08En from "../components/sections-content/content-08/en.json";
import content09En from "../components/sections-content/content-09/en.json";
import content10En from "../components/sections-content/content-10/en.json";
import content11En from "../components/sections-content/content-11/en.json";
import content12En from "../components/sections-content/content-12/en.json";
import content13En from "../components/sections-content/content-13/en.json";
import content14En from "../components/sections-content/content-14/en.json";
import content15En from "../components/sections-content/content-15/en.json";
import content16En from "../components/sections-content/content-16/en.json";
import content17En from "../components/sections-content/content-17/en.json";
import content18En from "../components/sections-content/content-18/en.json";
import content19En from "../components/sections-content/content-19/en.json";
import content20En from "../components/sections-content/content-20/en.json";
import content21En from "../components/sections-content/content-21/en.json";
import content22En from "../components/sections-content/content-22/en.json";
import content23En from "../components/sections-content/content-23/en.json";
import content24En from "../components/sections-content/content-24/en.json";
import content25En from "../components/sections-content/content-25/en.json";
import content26En from "../components/sections-content/content-26/en.json";
import content27En from "../components/sections-content/content-27/en.json";
import content28En from "../components/sections-content/content-28/en.json";
import content29En from "../components/sections-content/content-29/en.json";
import content30En from "../components/sections-content/content-30/en.json";
import content31En from "../components/sections-content/content-31/en.json";
import content32En from "../components/sections-content/content-32/en.json";
import cta01En from "../components/sections-cta/cta-01/en.json";
import cta02En from "../components/sections-cta/cta-02/en.json";
import cta03En from "../components/sections-cta/cta-03/en.json";
import cta04En from "../components/sections-cta/cta-04/en.json";
import cta05En from "../components/sections-cta/cta-05/en.json";
import cta06En from "../components/sections-cta/cta-06/en.json";
import cta07En from "../components/sections-cta/cta-07/en.json";
import cta08En from "../components/sections-cta/cta-08/en.json";
import cta09En from "../components/sections-cta/cta-09/en.json";
import cta10En from "../components/sections-cta/cta-10/en.json";
import cta11En from "../components/sections-cta/cta-11/en.json";
import cta12En from "../components/sections-cta/cta-12/en.json";
import customerStory01En from "../components/pages-customer-story/customer-story-01/en.json";
import customerStory02En from "../components/pages-customer-story/customer-story-02/en.json";
import customerStory03En from "../components/pages-customer-story/customer-story-03/en.json";
import customerStory04En from "../components/pages-customer-story/customer-story-04/en.json";
import customerStory05En from "../components/pages-customer-story/customer-story-05/en.json";
import customers01En from "../components/pages-customers/customers-01/en.json";
import customers02En from "../components/pages-customers/customers-02/en.json";
import customers03En from "../components/pages-customers/customers-03/en.json";
import customers04En from "../components/pages-customers/customers-04/en.json";
import dashboard01En from "../components/pages-dashboard/dashboard-01/en.json";
import dashboardHeaderEn from "../components/ui-molecules/dashboard/header/en.json";
import dashboardNavDocumentsEn from "../components/ui-molecules/dashboard/nav-documents/en.json";
import dashboardNavFavoritesEn from "../components/ui-molecules/dashboard/nav-favorites/en.json";
import dashboardNavMainEn from "../components/ui-molecules/dashboard/nav-main/en.json";
import dashboardNavUserEn from "../components/ui-molecules/dashboard/nav-user/en.json";
import dashboardNavWorkspacesEn from "../components/ui-molecules/dashboard/nav-workspaces/en.json";
import dashboardTeamSwitcherEn from "../components/ui-molecules/dashboard/team-switcher/en.json";
import dataTableEn from "../components/sections-data/data-table/en.json";
import dialog01En from "../components/sections-modals/dialog-01/en.json";
import dialog02En from "../components/sections-modals/dialog-02/en.json";
import dialog03En from "../components/sections-modals/dialog-03/en.json";
import dialog04En from "../components/sections-modals/dialog-04/en.json";
import dialog05En from "../components/sections-modals/dialog-05/en.json";
import dialog06En from "../components/sections-modals/dialog-06/en.json";
import dialog07En from "../components/sections-modals/dialog-07/en.json";
import dialog08En from "../components/sections-modals/dialog-08/en.json";
import dialog09En from "../components/sections-modals/dialog-09/en.json";
import dialog10En from "../components/sections-modals/dialog-10/en.json";
import dialog11En from "../components/sections-modals/dialog-11/en.json";
import dialog12En from "../components/sections-modals/dialog-12/en.json";
import ditherShaderEn from "../components/ui-effects/dither-shader/en.json";
import enterpriseFormEn from "../components/ui-molecules/contact-form/enterprise/en.json";
import error01En from "../components/pages-error/error-01/en.json";
import faq01En from "../components/sections-faq/faq-01/en.json";
import faq02En from "../components/sections-faq/faq-02/en.json";
import faq03En from "../components/sections-faq/faq-03/en.json";
import faq04En from "../components/sections-faq/faq-04/en.json";
import faq05En from "../components/sections-faq/faq-05/en.json";
import faq06En from "../components/sections-faq/faq-06/en.json";
import faq07En from "../components/sections-faq/faq-07/en.json";
import faq08En from "../components/sections-faq/faq-08/en.json";
import faq09En from "../components/sections-faq/faq-09/en.json";
import faq10En from "../components/sections-faq/faq-10/en.json";
import faq11En from "../components/sections-faq/faq-11/en.json";
import faq12En from "../components/sections-faq/faq-12/en.json";
import features01En from "../components/sections-features/features-01/en.json";
import features02En from "../components/sections-features/features-02/en.json";
import features03En from "../components/sections-features/features-03/en.json";
import features04En from "../components/sections-features/features-04/en.json";
import features05En from "../components/sections-features/features-05/en.json";
import features06En from "../components/sections-features/features-06/en.json";
import features07En from "../components/sections-features/features-07/en.json";
import features08En from "../components/sections-features/features-08/en.json";
import features09En from "../components/sections-features/features-09/en.json";
import features10En from "../components/sections-features/features-10/en.json";
import features11En from "../components/sections-features/features-11/en.json";
import features12En from "../components/sections-features/features-12/en.json";
import features13En from "../components/sections-features/features-13/en.json";
import features14En from "../components/sections-features/features-14/en.json";
import features15En from "../components/sections-features/features-15/en.json";
import features16En from "../components/sections-features/features-16/en.json";
import features17En from "../components/sections-features/features-17/en.json";
import features18En from "../components/sections-features/features-18/en.json";
import features19En from "../components/sections-features/features-19/en.json";
import features20En from "../components/sections-features/features-20/en.json";
import features21En from "../components/sections-features/features-21/en.json";
import features22En from "../components/sections-features/features-22/en.json";
import features23En from "../components/sections-features/features-23/en.json";
import features24En from "../components/sections-features/features-24/en.json";
import features25En from "../components/sections-features/features-25/en.json";
import features26En from "../components/sections-features/features-26/en.json";
import features27En from "../components/sections-features/features-27/en.json";
import features28En from "../components/sections-features/features-28/en.json";
import features29En from "../components/sections-features/features-29/en.json";
import features30En from "../components/sections-features/features-30/en.json";
import features31En from "../components/sections-features/features-31/en.json";
import features32En from "../components/sections-features/features-32/en.json";
import features33En from "../components/sections-features/features-33/en.json";
import features34En from "../components/sections-features/features-34/en.json";
import features35En from "../components/sections-features/features-35/en.json";
import features36En from "../components/sections-features/features-36/en.json";
import features37En from "../components/sections-features/features-37/en.json";
import features38En from "../components/sections-features/features-38/en.json";
import features39En from "../components/sections-features/features-39/en.json";
import features40En from "../components/sections-features/features-40/en.json";
import features41En from "../components/sections-features/features-41/en.json";
import features42En from "../components/sections-features/features-42/en.json";
import features43En from "../components/sections-features/features-43/en.json";
import featuresCarousel1En from "../components/sections-features-carousel/features-carousel-1/en.json";
import featuresCarousel2En from "../components/sections-features-carousel/features-carousel-2/en.json";
import featuresCarousel3En from "../components/sections-features-carousel/features-carousel-3/en.json";
import featuresCarousel4En from "../components/sections-features-carousel/features-carousel-4/en.json";
import featuresCarousel5En from "../components/sections-features-carousel/features-carousel-5/en.json";
import featuresExpandable1En from "../components/sections-features-expandable/features-expandable-1/en.json";
import featuresExpandable10En from "../components/sections-features-expandable/features-expandable-10/en.json";
import featuresExpandable11En from "../components/sections-features-expandable/features-expandable-11/en.json";
import featuresExpandable12En from "../components/sections-features-expandable/features-expandable-12/en.json";
import featuresExpandable13En from "../components/sections-features-expandable/features-expandable-13/en.json";
import featuresExpandable14En from "../components/sections-features-expandable/features-expandable-14/en.json";
import featuresExpandable15En from "../components/sections-features-expandable/features-expandable-15/en.json";
import featuresExpandable16En from "../components/sections-features-expandable/features-expandable-16/en.json";
import featuresExpandable17En from "../components/sections-features-expandable/features-expandable-17/en.json";
import featuresExpandable18En from "../components/sections-features-expandable/features-expandable-18/en.json";
import featuresExpandable19En from "../components/sections-features-expandable/features-expandable-19/en.json";
import featuresExpandable2En from "../components/sections-features-expandable/features-expandable-2/en.json";
import featuresExpandable20En from "../components/sections-features-expandable/features-expandable-20/en.json";
import featuresExpandable21En from "../components/sections-features-expandable/features-expandable-21/en.json";
import featuresExpandable22En from "../components/sections-features-expandable/features-expandable-22/en.json";
import featuresExpandable3En from "../components/sections-features-expandable/features-expandable-3/en.json";
import featuresExpandable4En from "../components/sections-features-expandable/features-expandable-4/en.json";
import featuresExpandable5En from "../components/sections-features-expandable/features-expandable-5/en.json";
import featuresExpandable6En from "../components/sections-features-expandable/features-expandable-6/en.json";
import featuresExpandable7En from "../components/sections-features-expandable/features-expandable-7/en.json";
import featuresExpandable8En from "../components/sections-features-expandable/features-expandable-8/en.json";
import featuresExpandable9En from "../components/sections-features-expandable/features-expandable-9/en.json";
import fileUpload01En from "../components/sections-file-upload/file-upload-01/en.json";
import fileUpload02En from "../components/sections-file-upload/file-upload-02/en.json";
import fileUpload03En from "../components/sections-file-upload/file-upload-03/en.json";
import fileUpload04En from "../components/sections-file-upload/file-upload-04/en.json";
import fileUpload05En from "../components/sections-file-upload/file-upload-05/en.json";
import fileUpload06En from "../components/sections-file-upload/file-upload-06/en.json";
import forgotPasswordEn from "../components/sections-auth/forgot-password/en.json";
import forgotPassword01En from "../components/pages-forgot-password/forgot-password-01/en.json";
import forgotPassword02En from "../components/sections-auth/forgot-password-02/en.json";
import forgotPassword03En from "../components/sections-auth/forgot-password-03/en.json";
import forgotPassword04En from "../components/sections-auth/forgot-password-04/en.json";
import forgotPassword05En from "../components/sections-auth/forgot-password-05/en.json";
import formLayout01En from "../components/sections-form/form-layout-01/en.json";
import formLayout02En from "../components/sections-form/form-layout-02/en.json";
import formLayout03En from "../components/sections-form/form-layout-03/en.json";
import formLayout04En from "../components/sections-form/form-layout-04/en.json";
import formLayout05En from "../components/sections-form/form-layout-05/en.json";
import gridList01En from "../components/sections-lists/grid-list-01/en.json";
import gridList02En from "../components/sections-lists/grid-list-02/en.json";
import gridList03En from "../components/sections-lists/grid-list-03/en.json";
import header1En from "../components/layouts/_shared/site-headers/header-1/en.json";
import header10En from "../components/layouts/_shared/site-headers/header-10/en.json";
import header2En from "../components/layouts/_shared/site-headers/header-2/en.json";
import header3En from "../components/layouts/_shared/site-headers/header-3/en.json";
import header4En from "../components/layouts/_shared/site-headers/header-4/en.json";
import header5En from "../components/layouts/_shared/site-headers/header-5/en.json";
import header6En from "../components/layouts/_shared/site-headers/header-6/en.json";
import header7En from "../components/layouts/_shared/site-headers/header-7/en.json";
import header8En from "../components/layouts/_shared/site-headers/header-8/en.json";
import hero1En from "../components/sections-hero/hero-1/en.json";
import hero10En from "../components/sections-hero/hero-10/en.json";
import hero11En from "../components/sections-hero/hero-11/en.json";
import hero12En from "../components/sections-hero/hero-12/en.json";
import hero13En from "../components/sections-hero/hero-13/en.json";
import hero14En from "../components/sections-hero/hero-14/en.json";
import hero15En from "../components/sections-hero/hero-15/en.json";
import hero16En from "../components/sections-hero/hero-16/en.json";
import hero17En from "../components/sections-hero/hero-17/en.json";
import hero18En from "../components/sections-hero/hero-18/en.json";
import hero19En from "../components/sections-hero/hero-19/en.json";
import hero2En from "../components/sections-hero/hero-2/en.json";
import hero20En from "../components/sections-hero/hero-20/en.json";
import hero21En from "../components/sections-hero/hero-21/en.json";
import hero22En from "../components/sections-hero/hero-22/en.json";
import hero23En from "../components/sections-hero/hero-23/en.json";
import hero24En from "../components/sections-hero/hero-24/en.json";
import hero25En from "../components/sections-hero/hero-25/en.json";
import hero3En from "../components/sections-hero/hero-3/en.json";
import hero4En from "../components/sections-hero/hero-4/en.json";
import hero5En from "../components/sections-hero/hero-5/en.json";
import hero6En from "../components/sections-hero/hero-6/en.json";
import hero7En from "../components/sections-hero/hero-7/en.json";
import hero8En from "../components/sections-hero/hero-8/en.json";
import hero9En from "../components/sections-hero/hero-9/en.json";
import heroVideoDialogEn from "../components/ui-effects/hero-video-dialog/en.json";
import howItWorks1En from "../components/sections-how-it-works/how-it-works-1/en.json";
import howItWorks2En from "../components/sections-how-it-works/how-it-works-2/en.json";
import howItWorks3En from "../components/sections-how-it-works/how-it-works-3/en.json";
import howItWorks4En from "../components/sections-how-it-works/how-it-works-4/en.json";
import howItWorks5En from "../components/sections-how-it-works/how-it-works-5/en.json";
import howItWorks6En from "../components/sections-how-it-works/how-it-works-6/en.json";
import howItWorks7En from "../components/sections-how-it-works/how-it-works-7/en.json";
import howItWorks8En from "../components/sections-how-it-works/how-it-works-8/en.json";
import howItWorks9En from "../components/sections-how-it-works/how-it-works-9/en.json";
import iconCloudEn from "../components/ui-effects/icon-cloud/en.json";
import integrations1En from "../components/sections-integrations/integrations-1/en.json";
import integrations10En from "../components/sections-integrations/integrations-10/en.json";
import integrations11En from "../components/sections-integrations/integrations-11/en.json";
import integrations12En from "../components/sections-integrations/integrations-12/en.json";
import integrations13En from "../components/sections-integrations/integrations-13/en.json";
import integrations14En from "../components/sections-integrations/integrations-14/en.json";
import integrations15En from "../components/sections-integrations/integrations-15/en.json";
import integrations16En from "../components/sections-integrations/integrations-16/en.json";
import integrations17En from "../components/sections-integrations/integrations-17/en.json";
import integrations18En from "../components/sections-integrations/integrations-18/en.json";
import integrations2En from "../components/sections-integrations/integrations-2/en.json";
import integrations5En from "../components/sections-integrations/integrations-5/en.json";
import integrations6En from "../components/sections-integrations/integrations-6/en.json";
import integrations7En from "../components/sections-integrations/integrations-7/en.json";
import integrations9En from "../components/sections-integrations/integrations-9/en.json";
import landing01En from "../components/pages-landing/landing-01/en.json";
import landing02En from "../components/pages-landing/landing-02/en.json";
import landing03En from "../components/pages-landing/landing-03/en.json";
import landing04En from "../components/pages-landing/landing-04/en.json";
import landing05En from "../components/pages-landing/landing-05/en.json";
import landing06En from "../components/pages-landing/landing-06/en.json";
import layoutTextFlipEn from "../components/ui-effects/layout-text-flip/en.json";
import localeSwitcherEn from "../components/layouts/_shared/locale-switcher/en.json";
import login01En from "../components/sections-auth/login-01/en.json";
import login02En from "../components/sections-auth/login-02/en.json";
import login03En from "../components/sections-auth/login-03/en.json";
import login04En from "../components/sections-auth/login-04/en.json";
import login05En from "../components/sections-auth/login-05/en.json";
import login06En from "../components/sections-auth/login-06/en.json";
import login07En from "../components/sections-auth/login-07/en.json";
import login08En from "../components/sections-auth/login-08/en.json";
import login09En from "../components/sections-auth/login-09/en.json";
import login10En from "../components/sections-auth/login-10/en.json";
import login11En from "../components/sections-auth/login-11/en.json";
import login12En from "../components/sections-auth/login-12/en.json";
import login13En from "../components/sections-auth/login-13/en.json";
import login14En from "../components/sections-auth/login-14/en.json";
import login15En from "../components/sections-auth/login-15/en.json";
import login16En from "../components/sections-auth/login-16/en.json";
import login17En from "../components/sections-auth/login-17/en.json";
import login18En from "../components/sections-auth/login-18/en.json";
import login19En from "../components/sections-auth/login-19/en.json";
import login20En from "../components/sections-auth/login-20/en.json";
import login21En from "../components/sections-auth/login-21/en.json";
import login22En from "../components/sections-auth/login-22/en.json";
import login23En from "../components/sections-auth/login-23/en.json";
import loginFormEn from "../components/ui-molecules/auth-form/login/en.json";
import logoCloud1En from "../components/sections-logo-cloud/logo-cloud-1/en.json";
import logoCloud10En from "../components/sections-logo-cloud/logo-cloud-10/en.json";
import logoCloud11En from "../components/sections-logo-cloud/logo-cloud-11/en.json";
import logoCloud12En from "../components/sections-logo-cloud/logo-cloud-12/en.json";
import logoCloud13En from "../components/sections-logo-cloud/logo-cloud-13/en.json";
import logoCloud14En from "../components/sections-logo-cloud/logo-cloud-14/en.json";
import logoCloud15En from "../components/sections-logo-cloud/logo-cloud-15/en.json";
import logoCloud2En from "../components/sections-logo-cloud/logo-cloud-2/en.json";
import logoCloud3En from "../components/sections-logo-cloud/logo-cloud-3/en.json";
import logoCloud4En from "../components/sections-logo-cloud/logo-cloud-4/en.json";
import logoCloud5En from "../components/sections-logo-cloud/logo-cloud-5/en.json";
import logoCloud6En from "../components/sections-logo-cloud/logo-cloud-6/en.json";
import logoCloud7En from "../components/sections-logo-cloud/logo-cloud-7/en.json";
import logoCloud8En from "../components/sections-logo-cloud/logo-cloud-8/en.json";
import logoCloud9En from "../components/sections-logo-cloud/logo-cloud-9/en.json";
import notFound01En from "../components/pages-not-found/not-found-01/en.json";
import onboarding01En from "../components/sections-onboarding/onboarding-01/en.json";
import onboarding02En from "../components/sections-onboarding/onboarding-02/en.json";
import onboarding03En from "../components/sections-onboarding/onboarding-03/en.json";
import onboarding04En from "../components/sections-onboarding/onboarding-04/en.json";
import onboarding07En from "../components/sections-onboarding/onboarding-07/en.json";
import pagesLogin01En from "../components/pages-login/login-01/en.json";
import pixelatedCanvasEn from "../components/ui-effects/pixelated-canvas/en.json";
import pricing01En from "../components/sections-pricing/pricing-01/en.json";
import pricing02En from "../components/sections-pricing/pricing-02/en.json";
import pricing03En from "../components/sections-pricing/pricing-03/en.json";
import pricing04En from "../components/sections-pricing/pricing-04/en.json";
import pricing05En from "../components/sections-pricing/pricing-05/en.json";
import pricing06En from "../components/sections-pricing/pricing-06/en.json";
import pricing07En from "../components/sections-pricing/pricing-07/en.json";
import pricing08En from "../components/sections-pricing/pricing-08/en.json";
import pricing09En from "../components/sections-pricing/pricing-09/en.json";
import pricingComparatorEn from "../components/sections-pricing/pricing-comparator/en.json";
import pricingComparator2En from "../components/sections-pricing/pricing-comparator-2/en.json";
import pricingComparator3En from "../components/sections-pricing/pricing-comparator-3/en.json";
import pricingComparator4En from "../components/sections-pricing/pricing-comparator-4/en.json";
import pricingPage01En from "../components/pages-pricing/pricing-page-01/en.json";
import pricingPage02En from "../components/pages-pricing/pricing-page-02/en.json";
import pricingPage03En from "../components/pages-pricing/pricing-page-03/en.json";
import pricingPage04En from "../components/pages-pricing/pricing-page-04/en.json";
import pricingPage05En from "../components/pages-pricing/pricing-page-05/en.json";
import product01En from "../components/pages-product/product-01/en.json";
import product02En from "../components/pages-product/product-02/en.json";
import quickActions01En from "../components/sections-dashboard/quick-actions-01/en.json";
import recentActivity01En from "../components/sections-dashboard/recent-activity-01/en.json";
import secondaryHero1En from "../components/sections-secondary-hero/secondary-hero-1/en.json";
import secondaryHero10En from "../components/sections-secondary-hero/secondary-hero-10/en.json";
import secondaryHero11En from "../components/sections-secondary-hero/secondary-hero-11/en.json";
import secondaryHero12En from "../components/sections-secondary-hero/secondary-hero-12/en.json";
import secondaryHero13En from "../components/sections-secondary-hero/secondary-hero-13/en.json";
import secondaryHero14En from "../components/sections-secondary-hero/secondary-hero-14/en.json";
import secondaryHero15En from "../components/sections-secondary-hero/secondary-hero-15/en.json";
import secondaryHero16En from "../components/sections-secondary-hero/secondary-hero-16/en.json";
import secondaryHero17En from "../components/sections-secondary-hero/secondary-hero-17/en.json";
import secondaryHero18En from "../components/sections-secondary-hero/secondary-hero-18/en.json";
import secondaryHero19En from "../components/sections-secondary-hero/secondary-hero-19/en.json";
import secondaryHero2En from "../components/sections-secondary-hero/secondary-hero-2/en.json";
import secondaryHero20En from "../components/sections-secondary-hero/secondary-hero-20/en.json";
import secondaryHero3En from "../components/sections-secondary-hero/secondary-hero-3/en.json";
import secondaryHero4En from "../components/sections-secondary-hero/secondary-hero-4/en.json";
import secondaryHero5En from "../components/sections-secondary-hero/secondary-hero-5/en.json";
import secondaryHero6En from "../components/sections-secondary-hero/secondary-hero-6/en.json";
import secondaryHero7En from "../components/sections-secondary-hero/secondary-hero-7/en.json";
import secondaryHero8En from "../components/sections-secondary-hero/secondary-hero-8/en.json";
import secondaryHero9En from "../components/sections-secondary-hero/secondary-hero-9/en.json";
import sectionCardsEn from "../components/ui-molecules/dashboard/kpi-cards/en.json";
import settingsDialogEn from "../components/sections-modals/settings-dialog/en.json";
import sidebarEn from "../components/layouts/sidebar-layout/en.json";
import sidebar01En from "../components/layouts/dashboard-layout/sidebars/sidebar-01/en.json";
import sidebar02En from "../components/layouts/dashboard-layout/sidebars/sidebar-02/en.json";
import sidebar03En from "../components/layouts/dashboard-layout/sidebars/sidebar-03/en.json";
import sidebar04En from "../components/layouts/dashboard-layout/sidebars/sidebar-04/en.json";
import sidebar05En from "../components/layouts/dashboard-layout/sidebars/sidebar-05/en.json";
import sidebar06En from "../components/layouts/dashboard-layout/sidebars/sidebar-06/en.json";
import sidebar07En from "../components/layouts/dashboard-layout/sidebars/sidebar-07/en.json";
import sidebar08En from "../components/layouts/dashboard-layout/sidebars/sidebar-08/en.json";
import sidebar09En from "../components/layouts/dashboard-layout/sidebars/sidebar-09/en.json";
import sidebarNavCollapseEn from "../components/ui-molecules/sidebar/nav-collapse/en.json";
import sidebarNavFooterEn from "../components/ui-molecules/sidebar/nav-footer/en.json";
import sidebarNavHeaderEn from "../components/ui-molecules/sidebar/nav-header/en.json";
import sidebarNavNotificationsEn from "../components/ui-molecules/sidebar/nav-notifications/en.json";
import sidebarNavUserEn from "../components/ui-molecules/sidebar/nav-user/en.json";
import sidebarTeamSwitcherGroupedEn from "../components/ui-molecules/sidebar/team-switcher/grouped/en.json";
import sidebarTeamSwitcherToggleEn from "../components/ui-molecules/sidebar/team-switcher/toggle/en.json";
import sidebarTriggerEn from "../components/ui-effects/sidebar-trigger/en.json";
import signup01En from "../components/pages-signup/signup-01/en.json";
import signupFormEn from "../components/ui-molecules/auth-form/signup/en.json";
import siteFooterEn from "../components/layouts/default-layout/site-footer/en.json";
import siteFooter10En from "../components/layouts/_shared/site-footers/site-footer-10/en.json";
import siteFooter11En from "../components/layouts/_shared/site-footers/site-footer-11/en.json";
import siteFooter12En from "../components/layouts/_shared/site-footers/site-footer-12/en.json";
import siteFooter13En from "../components/layouts/_shared/site-footers/site-footer-13/en.json";
import siteFooter2En from "../components/layouts/_shared/site-footers/site-footer-2/en.json";
import siteFooter3En from "../components/layouts/_shared/site-footers/site-footer-3/en.json";
import siteFooter4En from "../components/layouts/_shared/site-footers/site-footer-4/en.json";
import siteFooter5En from "../components/layouts/_shared/site-footers/site-footer-5/en.json";
import siteFooter6En from "../components/layouts/_shared/site-footers/site-footer-6/en.json";
import siteFooter7En from "../components/layouts/_shared/site-footers/site-footer-7/en.json";
import siteFooter8En from "../components/layouts/_shared/site-footers/site-footer-8/en.json";
import siteFooter9En from "../components/layouts/_shared/site-footers/site-footer-9/en.json";
import skipLinkEn from "../components/layouts/_shared/skip-link/en.json";
import solutions01En from "../components/pages-solutions/solutions-01/en.json";
import stats01En from "../components/sections-stats/stats-01/en.json";
import stats02En from "../components/sections-stats/stats-02/en.json";
import stats03En from "../components/sections-stats/stats-03/en.json";
import stats04En from "../components/sections-stats/stats-04/en.json";
import stats05En from "../components/sections-stats/stats-05/en.json";
import stats06En from "../components/sections-stats/stats-06/en.json";
import stats07En from "../components/sections-stats/stats-07/en.json";
import stats08En from "../components/sections-stats/stats-08/en.json";
import stats09En from "../components/ui-molecules/stat-tile/usage/en.json";
import stats10En from "../components/sections-stats/stats-10/en.json";
import stats11En from "../components/sections-stats/stats-11/en.json";
import stats12En from "../components/sections-stats/stats-12/en.json";
import stats13En from "../components/sections-stats/stats-13/en.json";
import stats14En from "../components/sections-stats/stats-14/en.json";
import stats15En from "../components/ui-molecules/stat-tile/projection/en.json";
import stats16En from "../components/sections-stats/stats-16/en.json";
import stats17En from "../components/sections-stats/stats-17/en.json";
import stats18En from "../components/sections-stats/stats-18/en.json";
import stats19En from "../components/sections-stats/stats-19/en.json";
import stats20En from "../components/sections-stats/stats-20/en.json";
import table01En from "../components/sections-data/table-01/en.json";
import table02En from "../components/sections-data/table-02/en.json";
import table03En from "../components/sections-data/table-03/en.json";
import table04En from "../components/sections-data/table-04/en.json";
import table05En from "../components/sections-data/table-05/en.json";
import team01En from "../components/sections-team/team-01/en.json";
import team02En from "../components/sections-team/team-02/en.json";
import team03En from "../components/sections-team/team-03/en.json";
import team04En from "../components/sections-team/team-04/en.json";
import team05En from "../components/sections-team/team-05/en.json";
import testimonials01En from "../components/sections-testimonials/testimonials-01/en.json";
import testimonials02En from "../components/sections-testimonials/testimonials-02/en.json";
import testimonials03En from "../components/sections-testimonials/testimonials-03/en.json";
import testimonials04En from "../components/sections-testimonials/testimonials-04/en.json";
import testimonials05En from "../components/sections-testimonials/testimonials-05/en.json";
import testimonials06En from "../components/sections-testimonials/testimonials-06/en.json";
import testimonials07En from "../components/sections-testimonials/testimonials-07/en.json";
import testimonials08En from "../components/sections-testimonials/testimonials-08/en.json";
import testimonials09En from "../components/sections-testimonials/testimonials-09/en.json";
import testimonials10En from "../components/sections-testimonials/testimonials-10/en.json";
import testimonials11En from "../components/sections-testimonials/testimonials-11/en.json";
import testimonials12En from "../components/sections-testimonials/testimonials-12/en.json";
import testimonials13En from "../components/sections-testimonials/testimonials-13/en.json";
import testimonials14En from "../components/sections-testimonials/testimonials-14/en.json";
import themeToggleEn from "../components/layouts/_shared/theme-toggle/en.json";
import timeline01En from "../components/sections-timelines/timeline-01/en.json";
import timeline02En from "../components/sections-timelines/timeline-02/en.json";
import trendBadgeEn from "../components/ui-molecules/trend-badge/en.json";
import tweetNotFoundEn from "../components/ui-effects/tweet-not-found/en.json";
import webcamPixelGridEn from "../components/ui-effects/webcam-pixel-grid/en.json";
import welcomeBanner01En from "../components/sections-dashboard/welcome-banner-01/en.json";
import worldMapEn from "../components/ui-effects/world-map/en.json";

const BLOCK_MESSAGES: Record<string, Record<string, unknown>> = {
  "3d-pin": _3dPinEn,
  "about-01": about01En,
  "about-02": about02En,
  "ai-01": ai01En,
  "ai-02": ai02En,
  "ai-03": ai03En,
  "ai-04": ai04En,
  "ai-05": ai05En,
  "animated-testimonials": animatedTestimonialsEn,
  "bento-1": bento1En,
  "bento-10": bento10En,
  "bento-11": bento11En,
  "bento-12": bento12En,
  "bento-13": bento13En,
  "bento-14": bento14En,
  "bento-2": bento2En,
  "bento-3": bento3En,
  "bento-4": bento4En,
  "bento-5": bento5En,
  "bento-6": bento6En,
  "bento-7": bento7En,
  "bento-8": bento8En,
  "bento-9": bento9En,
  "brand-01": brand01En,
  "chart-area-axes": chartAreaAxesEn,
  "chart-area-default": chartAreaDefaultEn,
  "chart-area-gradient": chartAreaGradientEn,
  "chart-area-icons": chartAreaIconsEn,
  "chart-area-interactive": chartAreaInteractiveEn,
  "chart-area-legend": chartAreaLegendEn,
  "chart-area-linear": chartAreaLinearEn,
  "chart-area-stacked": chartAreaStackedEn,
  "chart-area-stacked-expand": chartAreaStackedExpandEn,
  "chart-area-step": chartAreaStepEn,
  "chart-bar-active": chartBarActiveEn,
  "chart-bar-default": chartBarDefaultEn,
  "chart-bar-horizontal": chartBarHorizontalEn,
  "chart-bar-interactive": chartBarInteractiveEn,
  "chart-bar-label-custom": chartBarLabelCustomEn,
  "code-demo-1": codeDemo1En,
  "code-demo-2": codeDemo2En,
  "code-demo-3": codeDemo3En,
  "code-demo-4": codeDemo4En,
  "command-menu-01": commandMenu01En,
  "command-menu-02": commandMenu02En,
  "command-menu-03": commandMenu03En,
  "command-palette": commandPaletteEn,
  "contact-01": contact01En,
  "contact-page-01": contactPage01En,
  "contact-page-02": contactPage02En,
  "contact-page-03": contactPage03En,
  "contact-page-04": contactPage04En,
  "contact-page-05": contactPage05En,
  "contact-page-06": contactPage06En,
  "content-01": content01En,
  "content-02": content02En,
  "content-03": content03En,
  "content-04": content04En,
  "content-05": content05En,
  "content-06": content06En,
  "content-07": content07En,
  "content-08": content08En,
  "content-09": content09En,
  "content-10": content10En,
  "content-11": content11En,
  "content-12": content12En,
  "content-13": content13En,
  "content-14": content14En,
  "content-15": content15En,
  "content-16": content16En,
  "content-17": content17En,
  "content-18": content18En,
  "content-19": content19En,
  "content-20": content20En,
  "content-21": content21En,
  "content-22": content22En,
  "content-23": content23En,
  "content-24": content24En,
  "content-25": content25En,
  "content-26": content26En,
  "content-27": content27En,
  "content-28": content28En,
  "content-29": content29En,
  "content-30": content30En,
  "content-31": content31En,
  "content-32": content32En,
  "cta-01": cta01En,
  "cta-02": cta02En,
  "cta-03": cta03En,
  "cta-04": cta04En,
  "cta-05": cta05En,
  "cta-06": cta06En,
  "cta-07": cta07En,
  "cta-08": cta08En,
  "cta-09": cta09En,
  "cta-10": cta10En,
  "cta-11": cta11En,
  "cta-12": cta12En,
  "customer-story-01": customerStory01En,
  "customer-story-02": customerStory02En,
  "customer-story-03": customerStory03En,
  "customer-story-04": customerStory04En,
  "customer-story-05": customerStory05En,
  "customers-01": customers01En,
  "customers-02": customers02En,
  "customers-03": customers03En,
  "customers-04": customers04En,
  "dashboard-01": dashboard01En,
  "dashboard-header": dashboardHeaderEn,
  "dashboard-nav-documents": dashboardNavDocumentsEn,
  "dashboard-nav-favorites": dashboardNavFavoritesEn,
  "dashboard-nav-main": dashboardNavMainEn,
  "dashboard-nav-user": dashboardNavUserEn,
  "dashboard-nav-workspaces": dashboardNavWorkspacesEn,
  "dashboard-team-switcher": dashboardTeamSwitcherEn,
  "data-table": dataTableEn,
  "dialog-01": dialog01En,
  "dialog-02": dialog02En,
  "dialog-03": dialog03En,
  "dialog-04": dialog04En,
  "dialog-05": dialog05En,
  "dialog-06": dialog06En,
  "dialog-07": dialog07En,
  "dialog-08": dialog08En,
  "dialog-09": dialog09En,
  "dialog-10": dialog10En,
  "dialog-11": dialog11En,
  "dialog-12": dialog12En,
  "dither-shader": ditherShaderEn,
  "enterprise-form": enterpriseFormEn,
  "error-01": error01En,
  "faq-01": faq01En,
  "faq-02": faq02En,
  "faq-03": faq03En,
  "faq-04": faq04En,
  "faq-05": faq05En,
  "faq-06": faq06En,
  "faq-07": faq07En,
  "faq-08": faq08En,
  "faq-09": faq09En,
  "faq-10": faq10En,
  "faq-11": faq11En,
  "faq-12": faq12En,
  "features-01": features01En,
  "features-02": features02En,
  "features-03": features03En,
  "features-04": features04En,
  "features-05": features05En,
  "features-06": features06En,
  "features-07": features07En,
  "features-08": features08En,
  "features-09": features09En,
  "features-10": features10En,
  "features-11": features11En,
  "features-12": features12En,
  "features-13": features13En,
  "features-14": features14En,
  "features-15": features15En,
  "features-16": features16En,
  "features-17": features17En,
  "features-18": features18En,
  "features-19": features19En,
  "features-20": features20En,
  "features-21": features21En,
  "features-22": features22En,
  "features-23": features23En,
  "features-24": features24En,
  "features-25": features25En,
  "features-26": features26En,
  "features-27": features27En,
  "features-28": features28En,
  "features-29": features29En,
  "features-30": features30En,
  "features-31": features31En,
  "features-32": features32En,
  "features-33": features33En,
  "features-34": features34En,
  "features-35": features35En,
  "features-36": features36En,
  "features-37": features37En,
  "features-38": features38En,
  "features-39": features39En,
  "features-40": features40En,
  "features-41": features41En,
  "features-42": features42En,
  "features-43": features43En,
  "features-carousel-1": featuresCarousel1En,
  "features-carousel-2": featuresCarousel2En,
  "features-carousel-3": featuresCarousel3En,
  "features-carousel-4": featuresCarousel4En,
  "features-carousel-5": featuresCarousel5En,
  "features-expandable-1": featuresExpandable1En,
  "features-expandable-10": featuresExpandable10En,
  "features-expandable-11": featuresExpandable11En,
  "features-expandable-12": featuresExpandable12En,
  "features-expandable-13": featuresExpandable13En,
  "features-expandable-14": featuresExpandable14En,
  "features-expandable-15": featuresExpandable15En,
  "features-expandable-16": featuresExpandable16En,
  "features-expandable-17": featuresExpandable17En,
  "features-expandable-18": featuresExpandable18En,
  "features-expandable-19": featuresExpandable19En,
  "features-expandable-2": featuresExpandable2En,
  "features-expandable-20": featuresExpandable20En,
  "features-expandable-21": featuresExpandable21En,
  "features-expandable-22": featuresExpandable22En,
  "features-expandable-3": featuresExpandable3En,
  "features-expandable-4": featuresExpandable4En,
  "features-expandable-5": featuresExpandable5En,
  "features-expandable-6": featuresExpandable6En,
  "features-expandable-7": featuresExpandable7En,
  "features-expandable-8": featuresExpandable8En,
  "features-expandable-9": featuresExpandable9En,
  "file-upload-01": fileUpload01En,
  "file-upload-02": fileUpload02En,
  "file-upload-03": fileUpload03En,
  "file-upload-04": fileUpload04En,
  "file-upload-05": fileUpload05En,
  "file-upload-06": fileUpload06En,
  "forgot-password": forgotPasswordEn,
  "forgot-password-01": forgotPassword01En,
  "forgot-password-02": forgotPassword02En,
  "forgot-password-03": forgotPassword03En,
  "forgot-password-04": forgotPassword04En,
  "forgot-password-05": forgotPassword05En,
  "form-layout-01": formLayout01En,
  "form-layout-02": formLayout02En,
  "form-layout-03": formLayout03En,
  "form-layout-04": formLayout04En,
  "form-layout-05": formLayout05En,
  "grid-list-01": gridList01En,
  "grid-list-02": gridList02En,
  "grid-list-03": gridList03En,
  "header-1": header1En,
  "header-10": header10En,
  "header-2": header2En,
  "header-3": header3En,
  "header-4": header4En,
  "header-5": header5En,
  "header-6": header6En,
  "header-7": header7En,
  "header-8": header8En,
  "hero-1": hero1En,
  "hero-10": hero10En,
  "hero-11": hero11En,
  "hero-12": hero12En,
  "hero-13": hero13En,
  "hero-14": hero14En,
  "hero-15": hero15En,
  "hero-16": hero16En,
  "hero-17": hero17En,
  "hero-18": hero18En,
  "hero-19": hero19En,
  "hero-2": hero2En,
  "hero-20": hero20En,
  "hero-21": hero21En,
  "hero-22": hero22En,
  "hero-23": hero23En,
  "hero-24": hero24En,
  "hero-25": hero25En,
  "hero-3": hero3En,
  "hero-4": hero4En,
  "hero-5": hero5En,
  "hero-6": hero6En,
  "hero-7": hero7En,
  "hero-8": hero8En,
  "hero-9": hero9En,
  "hero-video-dialog": heroVideoDialogEn,
  "how-it-works-1": howItWorks1En,
  "how-it-works-2": howItWorks2En,
  "how-it-works-3": howItWorks3En,
  "how-it-works-4": howItWorks4En,
  "how-it-works-5": howItWorks5En,
  "how-it-works-6": howItWorks6En,
  "how-it-works-7": howItWorks7En,
  "how-it-works-8": howItWorks8En,
  "how-it-works-9": howItWorks9En,
  "icon-cloud": iconCloudEn,
  "integrations-1": integrations1En,
  "integrations-10": integrations10En,
  "integrations-11": integrations11En,
  "integrations-12": integrations12En,
  "integrations-13": integrations13En,
  "integrations-14": integrations14En,
  "integrations-15": integrations15En,
  "integrations-16": integrations16En,
  "integrations-17": integrations17En,
  "integrations-18": integrations18En,
  "integrations-2": integrations2En,
  "integrations-5": integrations5En,
  "integrations-6": integrations6En,
  "integrations-7": integrations7En,
  "integrations-9": integrations9En,
  "landing-01": landing01En,
  "landing-02": landing02En,
  "landing-03": landing03En,
  "landing-04": landing04En,
  "landing-05": landing05En,
  "landing-06": landing06En,
  "layout-text-flip": layoutTextFlipEn,
  "locale-switcher": localeSwitcherEn,
  "login-01": login01En,
  "login-02": login02En,
  "login-03": login03En,
  "login-04": login04En,
  "login-05": login05En,
  "login-06": login06En,
  "login-07": login07En,
  "login-08": login08En,
  "login-09": login09En,
  "login-10": login10En,
  "login-11": login11En,
  "login-12": login12En,
  "login-13": login13En,
  "login-14": login14En,
  "login-15": login15En,
  "login-16": login16En,
  "login-17": login17En,
  "login-18": login18En,
  "login-19": login19En,
  "login-20": login20En,
  "login-21": login21En,
  "login-22": login22En,
  "login-23": login23En,
  "login-form": loginFormEn,
  "logo-cloud-1": logoCloud1En,
  "logo-cloud-10": logoCloud10En,
  "logo-cloud-11": logoCloud11En,
  "logo-cloud-12": logoCloud12En,
  "logo-cloud-13": logoCloud13En,
  "logo-cloud-14": logoCloud14En,
  "logo-cloud-15": logoCloud15En,
  "logo-cloud-2": logoCloud2En,
  "logo-cloud-3": logoCloud3En,
  "logo-cloud-4": logoCloud4En,
  "logo-cloud-5": logoCloud5En,
  "logo-cloud-6": logoCloud6En,
  "logo-cloud-7": logoCloud7En,
  "logo-cloud-8": logoCloud8En,
  "logo-cloud-9": logoCloud9En,
  "not-found-01": notFound01En,
  "onboarding-01": onboarding01En,
  "onboarding-02": onboarding02En,
  "onboarding-03": onboarding03En,
  "onboarding-04": onboarding04En,
  "onboarding-07": onboarding07En,
  "pages-login-01": pagesLogin01En,
  "pixelated-canvas": pixelatedCanvasEn,
  "pricing-01": pricing01En,
  "pricing-02": pricing02En,
  "pricing-03": pricing03En,
  "pricing-04": pricing04En,
  "pricing-05": pricing05En,
  "pricing-06": pricing06En,
  "pricing-07": pricing07En,
  "pricing-08": pricing08En,
  "pricing-09": pricing09En,
  "pricing-comparator": pricingComparatorEn,
  "pricing-comparator-2": pricingComparator2En,
  "pricing-comparator-3": pricingComparator3En,
  "pricing-comparator-4": pricingComparator4En,
  "pricing-page-01": pricingPage01En,
  "pricing-page-02": pricingPage02En,
  "pricing-page-03": pricingPage03En,
  "pricing-page-04": pricingPage04En,
  "pricing-page-05": pricingPage05En,
  "product-01": product01En,
  "product-02": product02En,
  "quick-actions-01": quickActions01En,
  "recent-activity-01": recentActivity01En,
  "secondary-hero-1": secondaryHero1En,
  "secondary-hero-10": secondaryHero10En,
  "secondary-hero-11": secondaryHero11En,
  "secondary-hero-12": secondaryHero12En,
  "secondary-hero-13": secondaryHero13En,
  "secondary-hero-14": secondaryHero14En,
  "secondary-hero-15": secondaryHero15En,
  "secondary-hero-16": secondaryHero16En,
  "secondary-hero-17": secondaryHero17En,
  "secondary-hero-18": secondaryHero18En,
  "secondary-hero-19": secondaryHero19En,
  "secondary-hero-2": secondaryHero2En,
  "secondary-hero-20": secondaryHero20En,
  "secondary-hero-3": secondaryHero3En,
  "secondary-hero-4": secondaryHero4En,
  "secondary-hero-5": secondaryHero5En,
  "secondary-hero-6": secondaryHero6En,
  "secondary-hero-7": secondaryHero7En,
  "secondary-hero-8": secondaryHero8En,
  "secondary-hero-9": secondaryHero9En,
  "section-cards": sectionCardsEn,
  "settings-dialog": settingsDialogEn,
  sidebar: sidebarEn,
  "sidebar-01": sidebar01En,
  "sidebar-02": sidebar02En,
  "sidebar-03": sidebar03En,
  "sidebar-04": sidebar04En,
  "sidebar-05": sidebar05En,
  "sidebar-06": sidebar06En,
  "sidebar-07": sidebar07En,
  "sidebar-08": sidebar08En,
  "sidebar-09": sidebar09En,
  "sidebar-nav-collapse": sidebarNavCollapseEn,
  "sidebar-nav-footer": sidebarNavFooterEn,
  "sidebar-nav-header": sidebarNavHeaderEn,
  "sidebar-nav-notifications": sidebarNavNotificationsEn,
  "sidebar-nav-user": sidebarNavUserEn,
  "sidebar-team-switcher-grouped": sidebarTeamSwitcherGroupedEn,
  "sidebar-team-switcher-toggle": sidebarTeamSwitcherToggleEn,
  "sidebar-trigger": sidebarTriggerEn,
  "signup-01": signup01En,
  "signup-form": signupFormEn,
  "site-footer": siteFooterEn,
  "site-footer-10": siteFooter10En,
  "site-footer-11": siteFooter11En,
  "site-footer-12": siteFooter12En,
  "site-footer-13": siteFooter13En,
  "site-footer-2": siteFooter2En,
  "site-footer-3": siteFooter3En,
  "site-footer-4": siteFooter4En,
  "site-footer-5": siteFooter5En,
  "site-footer-6": siteFooter6En,
  "site-footer-7": siteFooter7En,
  "site-footer-8": siteFooter8En,
  "site-footer-9": siteFooter9En,
  "skip-link": skipLinkEn,
  "solutions-01": solutions01En,
  "stats-01": stats01En,
  "stats-02": stats02En,
  "stats-03": stats03En,
  "stats-04": stats04En,
  "stats-05": stats05En,
  "stats-06": stats06En,
  "stats-07": stats07En,
  "stats-08": stats08En,
  "stats-09": stats09En,
  "stats-10": stats10En,
  "stats-11": stats11En,
  "stats-12": stats12En,
  "stats-13": stats13En,
  "stats-14": stats14En,
  "stats-15": stats15En,
  "stats-16": stats16En,
  "stats-17": stats17En,
  "stats-18": stats18En,
  "stats-19": stats19En,
  "stats-20": stats20En,
  "table-01": table01En,
  "table-02": table02En,
  "table-03": table03En,
  "table-04": table04En,
  "table-05": table05En,
  "team-01": team01En,
  "team-02": team02En,
  "team-03": team03En,
  "team-04": team04En,
  "team-05": team05En,
  "testimonials-01": testimonials01En,
  "testimonials-02": testimonials02En,
  "testimonials-03": testimonials03En,
  "testimonials-04": testimonials04En,
  "testimonials-05": testimonials05En,
  "testimonials-06": testimonials06En,
  "testimonials-07": testimonials07En,
  "testimonials-08": testimonials08En,
  "testimonials-09": testimonials09En,
  "testimonials-10": testimonials10En,
  "testimonials-11": testimonials11En,
  "testimonials-12": testimonials12En,
  "testimonials-13": testimonials13En,
  "testimonials-14": testimonials14En,
  "theme-toggle": themeToggleEn,
  "timeline-01": timeline01En,
  "timeline-02": timeline02En,
  "trend-badge": trendBadgeEn,
  "tweet-not-found": tweetNotFoundEn,
  "webcam-pixel-grid": webcamPixelGridEn,
  "welcome-banner-01": welcomeBanner01En,
  "world-map": worldMapEn,
};

/**
 * Returns `{ "<block-key>": {...}, ... }` merged as-is. Non-English
 * locales fall back to the English sample — clients fill in real
 * translations per page when they customize.
 */
export function loadBlockMessages(): Record<string, unknown> {
  return { ...BLOCK_MESSAGES };
}
