// AUTO-GENERATED by scripts/generate-i18n-registry.mjs
// DO NOT EDIT — run `pnpm gen:i18n` to regenerate. Drift caught by `pnpm verify:i18n`.

import sidebar01En from "../components/layouts/dashboard-layout/sidebars/sidebar-01/en.json";
import sidebar02En from "../components/layouts/dashboard-layout/sidebars/sidebar-02/en.json";
import sidebar03En from "../components/layouts/dashboard-layout/sidebars/sidebar-03/en.json";
import sidebar04En from "../components/layouts/dashboard-layout/sidebars/sidebar-04/en.json";
import sidebar05En from "../components/layouts/dashboard-layout/sidebars/sidebar-05/en.json";
import sidebar06En from "../components/layouts/dashboard-layout/sidebars/sidebar-06/en.json";
import sidebar07En from "../components/layouts/dashboard-layout/sidebars/sidebar-07/en.json";
import sidebar08En from "../components/layouts/dashboard-layout/sidebars/sidebar-08/en.json";
import sidebar09En from "../components/layouts/dashboard-layout/sidebars/sidebar-09/en.json";
import siteFooterEn from "../components/layouts/default-layout/site-footer/en.json";
import localeSwitcherEn from "../components/layouts/_shared/locale-switcher/en.json";
import siteFooter10En from "../components/layouts/_shared/site-footers/site-footer-10/en.json";
import siteFooter11En from "../components/layouts/_shared/site-footers/site-footer-11/en.json";
import siteFooter12En from "../components/layouts/_shared/site-footers/site-footer-12/en.json";
import siteFooter13En from "../components/layouts/_shared/site-footers/site-footer-13/en.json";
import siteFooter2En from "../components/layouts/_shared/site-footers/site-footer-2/en.json";
import siteFooter3En from "../components/layouts/_shared/site-footers/site-footer-3/en.json";
import siteFooter4En from "../components/layouts/_shared/site-footers/site-footer-4/en.json";
import siteFooter5En from "../components/layouts/_shared/site-footers/site-footer-5/en.json";
import siteFooter6En from "../components/layouts/_shared/site-footers/site-footer-6/en.json";
import siteFooter7En from "../components/layouts/_shared/site-footers/site-footer-7/en.json";
import siteFooter8En from "../components/layouts/_shared/site-footers/site-footer-8/en.json";
import siteFooter9En from "../components/layouts/_shared/site-footers/site-footer-9/en.json";
import header1En from "../components/layouts/_shared/site-headers/header-1/en.json";
import header10En from "../components/layouts/_shared/site-headers/header-10/en.json";
import header2En from "../components/layouts/_shared/site-headers/header-2/en.json";
import header3En from "../components/layouts/_shared/site-headers/header-3/en.json";
import header4En from "../components/layouts/_shared/site-headers/header-4/en.json";
import header5En from "../components/layouts/_shared/site-headers/header-5/en.json";
import header6En from "../components/layouts/_shared/site-headers/header-6/en.json";
import header7En from "../components/layouts/_shared/site-headers/header-7/en.json";
import header8En from "../components/layouts/_shared/site-headers/header-8/en.json";
import skipLinkEn from "../components/layouts/_shared/skip-link/en.json";
import themeToggleEn from "../components/layouts/_shared/theme-toggle/en.json";
import sidebarEn from "../components/layouts/sidebar-layout/en.json";
import about01En from "../components/pages-about/about-01/en.json";
import about02En from "../components/pages-about/about-02/en.json";
import brand01En from "../components/pages-brand/brand-01/en.json";
import contactPage01En from "../components/pages-contact/contact-page-01/en.json";
import contactPage02En from "../components/pages-contact/contact-page-02/en.json";
import contactPage03En from "../components/pages-contact/contact-page-03/en.json";
import contactPage04En from "../components/pages-contact/contact-page-04/en.json";
import contactPage05En from "../components/pages-contact/contact-page-05/en.json";
import contactPage06En from "../components/pages-contact/contact-page-06/en.json";
import customers01En from "../components/pages-customers/customers-01/en.json";
import customers02En from "../components/pages-customers/customers-02/en.json";
import customers03En from "../components/pages-customers/customers-03/en.json";
import customers04En from "../components/pages-customers/customers-04/en.json";
import customerStory01En from "../components/pages-customer-story/customer-story-01/en.json";
import customerStory02En from "../components/pages-customer-story/customer-story-02/en.json";
import customerStory03En from "../components/pages-customer-story/customer-story-03/en.json";
import customerStory04En from "../components/pages-customer-story/customer-story-04/en.json";
import customerStory05En from "../components/pages-customer-story/customer-story-05/en.json";
import dashboard01En from "../components/pages-dashboard/dashboard-01/en.json";
import error01En from "../components/pages-error/error-01/en.json";
import forgotPassword01En from "../components/pages-forgot-password/forgot-password-01/en.json";
import landing01En from "../components/pages-landing/landing-01/en.json";
import landing02En from "../components/pages-landing/landing-02/en.json";
import landing03En from "../components/pages-landing/landing-03/en.json";
import landing04En from "../components/pages-landing/landing-04/en.json";
import landing05En from "../components/pages-landing/landing-05/en.json";
import landing06En from "../components/pages-landing/landing-06/en.json";
import pagesLogin01En from "../components/pages-login/login-01/en.json";
import notFound01En from "../components/pages-not-found/not-found-01/en.json";
import pricingPage01En from "../components/pages-pricing/pricing-page-01/en.json";
import pricingPage02En from "../components/pages-pricing/pricing-page-02/en.json";
import pricingPage03En from "../components/pages-pricing/pricing-page-03/en.json";
import pricingPage04En from "../components/pages-pricing/pricing-page-04/en.json";
import pricingPage05En from "../components/pages-pricing/pricing-page-05/en.json";
import product01En from "../components/pages-product/product-01/en.json";
import product02En from "../components/pages-product/product-02/en.json";
import signup01En from "../components/pages-signup/signup-01/en.json";
import solutions01En from "../components/pages-solutions/solutions-01/en.json";
import ai01En from "../components/sections-ai/ai-01/en.json";
import ai02En from "../components/sections-ai/ai-02/en.json";
import ai03En from "../components/sections-ai/ai-03/en.json";
import ai04En from "../components/sections-ai/ai-04/en.json";
import ai05En from "../components/sections-ai/ai-05/en.json";
import forgotPasswordEn from "../components/sections-auth/forgot-password/en.json";
import forgotPassword02En from "../components/sections-auth/forgot-password-02/en.json";
import forgotPassword03En from "../components/sections-auth/forgot-password-03/en.json";
import forgotPassword04En from "../components/sections-auth/forgot-password-04/en.json";
import forgotPassword05En from "../components/sections-auth/forgot-password-05/en.json";
import login01En from "../components/sections-auth/login-01/en.json";
import login02En from "../components/sections-auth/login-02/en.json";
import login03En from "../components/sections-auth/login-03/en.json";
import login04En from "../components/sections-auth/login-04/en.json";
import login05En from "../components/sections-auth/login-05/en.json";
import login06En from "../components/sections-auth/login-06/en.json";
import login07En from "../components/sections-auth/login-07/en.json";
import login08En from "../components/sections-auth/login-08/en.json";
import login09En from "../components/sections-auth/login-09/en.json";
import login10En from "../components/sections-auth/login-10/en.json";
import login11En from "../components/sections-auth/login-11/en.json";
import login12En from "../components/sections-auth/login-12/en.json";
import login13En from "../components/sections-auth/login-13/en.json";
import login14En from "../components/sections-auth/login-14/en.json";
import login15En from "../components/sections-auth/login-15/en.json";
import login16En from "../components/sections-auth/login-16/en.json";
import login17En from "../components/sections-auth/login-17/en.json";
import login18En from "../components/sections-auth/login-18/en.json";
import login19En from "../components/sections-auth/login-19/en.json";
import login20En from "../components/sections-auth/login-20/en.json";
import login21En from "../components/sections-auth/login-21/en.json";
import login22En from "../components/sections-auth/login-22/en.json";
import login23En from "../components/sections-auth/login-23/en.json";
import bento01En from "../components/sections-bento/bento-01/en.json";
import bento02En from "../components/sections-bento/bento-02/en.json";
import bento03En from "../components/sections-bento/bento-03/en.json";
import bento04En from "../components/sections-bento/bento-04/en.json";
import bento05En from "../components/sections-bento/bento-05/en.json";
import bento06En from "../components/sections-bento/bento-06/en.json";
import bento07En from "../components/sections-bento/bento-07/en.json";
import bento08En from "../components/sections-bento/bento-08/en.json";
import bento09En from "../components/sections-bento/bento-09/en.json";
import bento10En from "../components/sections-bento/bento-10/en.json";
import bento11En from "../components/sections-bento/bento-11/en.json";
import bento12En from "../components/sections-bento/bento-12/en.json";
import bento13En from "../components/sections-bento/bento-13/en.json";
import bento14En from "../components/sections-bento/bento-14/en.json";
import codeDemo01En from "../components/sections-code-demo/code-demo-01/en.json";
import codeDemo02En from "../components/sections-code-demo/code-demo-02/en.json";
import codeDemo03En from "../components/sections-code-demo/code-demo-03/en.json";
import codeDemo04En from "../components/sections-code-demo/code-demo-04/en.json";
import contact01En from "../components/sections-contact/contact-01/en.json";
import content01En from "../components/sections-content/content-01/en.json";
import content02En from "../components/sections-content/content-02/en.json";
import content03En from "../components/sections-content/content-03/en.json";
import content04En from "../components/sections-content/content-04/en.json";
import content05En from "../components/sections-content/content-05/en.json";
import content06En from "../components/sections-content/content-06/en.json";
import content07En from "../components/sections-content/content-07/en.json";
import content08En from "../components/sections-content/content-08/en.json";
import content09En from "../components/sections-content/content-09/en.json";
import content10En from "../components/sections-content/content-10/en.json";
import content11En from "../components/sections-content/content-11/en.json";
import content12En from "../components/sections-content/content-12/en.json";
import content13En from "../components/sections-content/content-13/en.json";
import content14En from "../components/sections-content/content-14/en.json";
import content15En from "../components/sections-content/content-15/en.json";
import content16En from "../components/sections-content/content-16/en.json";
import content17En from "../components/sections-content/content-17/en.json";
import content18En from "../components/sections-content/content-18/en.json";
import content19En from "../components/sections-content/content-19/en.json";
import content20En from "../components/sections-content/content-20/en.json";
import content21En from "../components/sections-content/content-21/en.json";
import content22En from "../components/sections-content/content-22/en.json";
import content23En from "../components/sections-content/content-23/en.json";
import content24En from "../components/sections-content/content-24/en.json";
import content25En from "../components/sections-content/content-25/en.json";
import content26En from "../components/sections-content/content-26/en.json";
import content27En from "../components/sections-content/content-27/en.json";
import content28En from "../components/sections-content/content-28/en.json";
import content29En from "../components/sections-content/content-29/en.json";
import content30En from "../components/sections-content/content-30/en.json";
import content31En from "../components/sections-content/content-31/en.json";
import content32En from "../components/sections-content/content-32/en.json";
import cta01En from "../components/sections-cta/cta-01/en.json";
import cta02En from "../components/sections-cta/cta-02/en.json";
import cta03En from "../components/sections-cta/cta-03/en.json";
import cta04En from "../components/sections-cta/cta-04/en.json";
import cta05En from "../components/sections-cta/cta-05/en.json";
import cta06En from "../components/sections-cta/cta-06/en.json";
import cta07En from "../components/sections-cta/cta-07/en.json";
import cta08En from "../components/sections-cta/cta-08/en.json";
import cta09En from "../components/sections-cta/cta-09/en.json";
import cta10En from "../components/sections-cta/cta-10/en.json";
import cta11En from "../components/sections-cta/cta-11/en.json";
import cta12En from "../components/sections-cta/cta-12/en.json";
import quickActions01En from "../components/sections-dashboard/quick-actions-01/en.json";
import recentActivity01En from "../components/sections-dashboard/recent-activity-01/en.json";
import welcomeBanner01En from "../components/sections-dashboard/welcome-banner-01/en.json";
import dataTableEn from "../components/sections-data/data-table/en.json";
import table01En from "../components/sections-data/table-01/en.json";
import table02En from "../components/sections-data/table-02/en.json";
import table03En from "../components/sections-data/table-03/en.json";
import table04En from "../components/sections-data/table-04/en.json";
import table05En from "../components/sections-data/table-05/en.json";
import faq01En from "../components/sections-faq/faq-01/en.json";
import faq02En from "../components/sections-faq/faq-02/en.json";
import faq03En from "../components/sections-faq/faq-03/en.json";
import faq04En from "../components/sections-faq/faq-04/en.json";
import faq05En from "../components/sections-faq/faq-05/en.json";
import faq06En from "../components/sections-faq/faq-06/en.json";
import faq07En from "../components/sections-faq/faq-07/en.json";
import faq08En from "../components/sections-faq/faq-08/en.json";
import faq09En from "../components/sections-faq/faq-09/en.json";
import faq10En from "../components/sections-faq/faq-10/en.json";
import faq11En from "../components/sections-faq/faq-11/en.json";
import faq12En from "../components/sections-faq/faq-12/en.json";
import features01En from "../components/sections-features/features-01/en.json";
import features02En from "../components/sections-features/features-02/en.json";
import features03En from "../components/sections-features/features-03/en.json";
import features04En from "../components/sections-features/features-04/en.json";
import features05En from "../components/sections-features/features-05/en.json";
import features06En from "../components/sections-features/features-06/en.json";
import features07En from "../components/sections-features/features-07/en.json";
import features08En from "../components/sections-features/features-08/en.json";
import features09En from "../components/sections-features/features-09/en.json";
import features10En from "../components/sections-features/features-10/en.json";
import features11En from "../components/sections-features/features-11/en.json";
import features12En from "../components/sections-features/features-12/en.json";
import features13En from "../components/sections-features/features-13/en.json";
import features14En from "../components/sections-features/features-14/en.json";
import features15En from "../components/sections-features/features-15/en.json";
import features16En from "../components/sections-features/features-16/en.json";
import features17En from "../components/sections-features/features-17/en.json";
import features18En from "../components/sections-features/features-18/en.json";
import features19En from "../components/sections-features/features-19/en.json";
import features20En from "../components/sections-features/features-20/en.json";
import features21En from "../components/sections-features/features-21/en.json";
import features22En from "../components/sections-features/features-22/en.json";
import features23En from "../components/sections-features/features-23/en.json";
import features24En from "../components/sections-features/features-24/en.json";
import features25En from "../components/sections-features/features-25/en.json";
import features26En from "../components/sections-features/features-26/en.json";
import features27En from "../components/sections-features/features-27/en.json";
import features28En from "../components/sections-features/features-28/en.json";
import features29En from "../components/sections-features/features-29/en.json";
import features30En from "../components/sections-features/features-30/en.json";
import features31En from "../components/sections-features/features-31/en.json";
import features32En from "../components/sections-features/features-32/en.json";
import features33En from "../components/sections-features/features-33/en.json";
import features34En from "../components/sections-features/features-34/en.json";
import features35En from "../components/sections-features/features-35/en.json";
import features36En from "../components/sections-features/features-36/en.json";
import features37En from "../components/sections-features/features-37/en.json";
import features38En from "../components/sections-features/features-38/en.json";
import features39En from "../components/sections-features/features-39/en.json";
import features40En from "../components/sections-features/features-40/en.json";
import features41En from "../components/sections-features/features-41/en.json";
import features42En from "../components/sections-features/features-42/en.json";
import features43En from "../components/sections-features/features-43/en.json";
import featuresCarousel01En from "../components/sections-features-carousel/features-carousel-01/en.json";
import featuresCarousel02En from "../components/sections-features-carousel/features-carousel-02/en.json";
import featuresCarousel03En from "../components/sections-features-carousel/features-carousel-03/en.json";
import featuresCarousel04En from "../components/sections-features-carousel/features-carousel-04/en.json";
import featuresCarousel05En from "../components/sections-features-carousel/features-carousel-05/en.json";
import featuresExpandable01En from "../components/sections-features-expandable/features-expandable-01/en.json";
import featuresExpandable02En from "../components/sections-features-expandable/features-expandable-02/en.json";
import featuresExpandable03En from "../components/sections-features-expandable/features-expandable-03/en.json";
import featuresExpandable04En from "../components/sections-features-expandable/features-expandable-04/en.json";
import featuresExpandable05En from "../components/sections-features-expandable/features-expandable-05/en.json";
import featuresExpandable06En from "../components/sections-features-expandable/features-expandable-06/en.json";
import featuresExpandable07En from "../components/sections-features-expandable/features-expandable-07/en.json";
import featuresExpandable08En from "../components/sections-features-expandable/features-expandable-08/en.json";
import featuresExpandable09En from "../components/sections-features-expandable/features-expandable-09/en.json";
import featuresExpandable10En from "../components/sections-features-expandable/features-expandable-10/en.json";
import featuresExpandable11En from "../components/sections-features-expandable/features-expandable-11/en.json";
import featuresExpandable12En from "../components/sections-features-expandable/features-expandable-12/en.json";
import featuresExpandable13En from "../components/sections-features-expandable/features-expandable-13/en.json";
import featuresExpandable14En from "../components/sections-features-expandable/features-expandable-14/en.json";
import featuresExpandable15En from "../components/sections-features-expandable/features-expandable-15/en.json";
import featuresExpandable16En from "../components/sections-features-expandable/features-expandable-16/en.json";
import featuresExpandable17En from "../components/sections-features-expandable/features-expandable-17/en.json";
import featuresExpandable18En from "../components/sections-features-expandable/features-expandable-18/en.json";
import featuresExpandable19En from "../components/sections-features-expandable/features-expandable-19/en.json";
import featuresExpandable20En from "../components/sections-features-expandable/features-expandable-20/en.json";
import featuresExpandable21En from "../components/sections-features-expandable/features-expandable-21/en.json";
import featuresExpandable22En from "../components/sections-features-expandable/features-expandable-22/en.json";
import fileUpload01En from "../components/sections-file-upload/file-upload-01/en.json";
import fileUpload02En from "../components/sections-file-upload/file-upload-02/en.json";
import fileUpload03En from "../components/sections-file-upload/file-upload-03/en.json";
import fileUpload04En from "../components/sections-file-upload/file-upload-04/en.json";
import fileUpload05En from "../components/sections-file-upload/file-upload-05/en.json";
import fileUpload06En from "../components/sections-file-upload/file-upload-06/en.json";
import formLayout01En from "../components/sections-form/form-layout-01/en.json";
import formLayout02En from "../components/sections-form/form-layout-02/en.json";
import formLayout03En from "../components/sections-form/form-layout-03/en.json";
import formLayout04En from "../components/sections-form/form-layout-04/en.json";
import formLayout05En from "../components/sections-form/form-layout-05/en.json";
import hero01En from "../components/sections-hero/hero-01/en.json";
import hero02En from "../components/sections-hero/hero-02/en.json";
import hero03En from "../components/sections-hero/hero-03/en.json";
import hero04En from "../components/sections-hero/hero-04/en.json";
import hero05En from "../components/sections-hero/hero-05/en.json";
import hero06En from "../components/sections-hero/hero-06/en.json";
import hero07En from "../components/sections-hero/hero-07/en.json";
import hero08En from "../components/sections-hero/hero-08/en.json";
import hero09En from "../components/sections-hero/hero-09/en.json";
import hero10En from "../components/sections-hero/hero-10/en.json";
import hero11En from "../components/sections-hero/hero-11/en.json";
import hero12En from "../components/sections-hero/hero-12/en.json";
import hero13En from "../components/sections-hero/hero-13/en.json";
import hero14En from "../components/sections-hero/hero-14/en.json";
import hero15En from "../components/sections-hero/hero-15/en.json";
import hero16En from "../components/sections-hero/hero-16/en.json";
import hero17En from "../components/sections-hero/hero-17/en.json";
import hero18En from "../components/sections-hero/hero-18/en.json";
import hero19En from "../components/sections-hero/hero-19/en.json";
import hero20En from "../components/sections-hero/hero-20/en.json";
import hero21En from "../components/sections-hero/hero-21/en.json";
import hero22En from "../components/sections-hero/hero-22/en.json";
import hero23En from "../components/sections-hero/hero-23/en.json";
import hero24En from "../components/sections-hero/hero-24/en.json";
import hero25En from "../components/sections-hero/hero-25/en.json";
import howItWorks01En from "../components/sections-how-it-works/how-it-works-01/en.json";
import howItWorks02En from "../components/sections-how-it-works/how-it-works-02/en.json";
import howItWorks03En from "../components/sections-how-it-works/how-it-works-03/en.json";
import howItWorks04En from "../components/sections-how-it-works/how-it-works-04/en.json";
import howItWorks05En from "../components/sections-how-it-works/how-it-works-05/en.json";
import howItWorks06En from "../components/sections-how-it-works/how-it-works-06/en.json";
import howItWorks07En from "../components/sections-how-it-works/how-it-works-07/en.json";
import howItWorks08En from "../components/sections-how-it-works/how-it-works-08/en.json";
import howItWorks09En from "../components/sections-how-it-works/how-it-works-09/en.json";
import integrations01En from "../components/sections-integrations/integrations-01/en.json";
import integrations02En from "../components/sections-integrations/integrations-02/en.json";
import integrations05En from "../components/sections-integrations/integrations-05/en.json";
import integrations06En from "../components/sections-integrations/integrations-06/en.json";
import integrations07En from "../components/sections-integrations/integrations-07/en.json";
import integrations09En from "../components/sections-integrations/integrations-09/en.json";
import integrations10En from "../components/sections-integrations/integrations-10/en.json";
import integrations11En from "../components/sections-integrations/integrations-11/en.json";
import integrations12En from "../components/sections-integrations/integrations-12/en.json";
import integrations13En from "../components/sections-integrations/integrations-13/en.json";
import integrations14En from "../components/sections-integrations/integrations-14/en.json";
import integrations15En from "../components/sections-integrations/integrations-15/en.json";
import integrations16En from "../components/sections-integrations/integrations-16/en.json";
import integrations17En from "../components/sections-integrations/integrations-17/en.json";
import integrations18En from "../components/sections-integrations/integrations-18/en.json";
import gridList01En from "../components/sections-lists/grid-list-01/en.json";
import gridList02En from "../components/sections-lists/grid-list-02/en.json";
import gridList03En from "../components/sections-lists/grid-list-03/en.json";
import logoCloud01En from "../components/sections-logo-cloud/logo-cloud-01/en.json";
import logoCloud02En from "../components/sections-logo-cloud/logo-cloud-02/en.json";
import logoCloud03En from "../components/sections-logo-cloud/logo-cloud-03/en.json";
import logoCloud04En from "../components/sections-logo-cloud/logo-cloud-04/en.json";
import logoCloud05En from "../components/sections-logo-cloud/logo-cloud-05/en.json";
import logoCloud06En from "../components/sections-logo-cloud/logo-cloud-06/en.json";
import logoCloud07En from "../components/sections-logo-cloud/logo-cloud-07/en.json";
import logoCloud08En from "../components/sections-logo-cloud/logo-cloud-08/en.json";
import logoCloud09En from "../components/sections-logo-cloud/logo-cloud-09/en.json";
import logoCloud10En from "../components/sections-logo-cloud/logo-cloud-10/en.json";
import logoCloud11En from "../components/sections-logo-cloud/logo-cloud-11/en.json";
import logoCloud12En from "../components/sections-logo-cloud/logo-cloud-12/en.json";
import logoCloud13En from "../components/sections-logo-cloud/logo-cloud-13/en.json";
import logoCloud14En from "../components/sections-logo-cloud/logo-cloud-14/en.json";
import logoCloud15En from "../components/sections-logo-cloud/logo-cloud-15/en.json";
import dialog01En from "../components/sections-modals/dialog-01/en.json";
import dialog02En from "../components/sections-modals/dialog-02/en.json";
import dialog03En from "../components/sections-modals/dialog-03/en.json";
import dialog04En from "../components/sections-modals/dialog-04/en.json";
import dialog05En from "../components/sections-modals/dialog-05/en.json";
import dialog06En from "../components/sections-modals/dialog-06/en.json";
import dialog07En from "../components/sections-modals/dialog-07/en.json";
import dialog08En from "../components/sections-modals/dialog-08/en.json";
import dialog09En from "../components/sections-modals/dialog-09/en.json";
import dialog10En from "../components/sections-modals/dialog-10/en.json";
import dialog11En from "../components/sections-modals/dialog-11/en.json";
import dialog12En from "../components/sections-modals/dialog-12/en.json";
import onboarding01En from "../components/sections-onboarding/onboarding-01/en.json";
import onboarding02En from "../components/sections-onboarding/onboarding-02/en.json";
import onboarding03En from "../components/sections-onboarding/onboarding-03/en.json";
import onboarding04En from "../components/sections-onboarding/onboarding-04/en.json";
import onboarding07En from "../components/sections-onboarding/onboarding-07/en.json";
import pricing01En from "../components/sections-pricing/pricing-01/en.json";
import pricing02En from "../components/sections-pricing/pricing-02/en.json";
import pricing03En from "../components/sections-pricing/pricing-03/en.json";
import pricing04En from "../components/sections-pricing/pricing-04/en.json";
import pricing05En from "../components/sections-pricing/pricing-05/en.json";
import pricing06En from "../components/sections-pricing/pricing-06/en.json";
import pricing07En from "../components/sections-pricing/pricing-07/en.json";
import pricing08En from "../components/sections-pricing/pricing-08/en.json";
import pricing09En from "../components/sections-pricing/pricing-09/en.json";
import pricingComparatorEn from "../components/sections-pricing/pricing-comparator/en.json";
import pricingComparator02En from "../components/sections-pricing/pricing-comparator-02/en.json";
import pricingComparator03En from "../components/sections-pricing/pricing-comparator-03/en.json";
import pricingComparator04En from "../components/sections-pricing/pricing-comparator-04/en.json";
import secondaryHero01En from "../components/sections-secondary-hero/secondary-hero-01/en.json";
import secondaryHero02En from "../components/sections-secondary-hero/secondary-hero-02/en.json";
import secondaryHero03En from "../components/sections-secondary-hero/secondary-hero-03/en.json";
import secondaryHero04En from "../components/sections-secondary-hero/secondary-hero-04/en.json";
import secondaryHero05En from "../components/sections-secondary-hero/secondary-hero-05/en.json";
import secondaryHero06En from "../components/sections-secondary-hero/secondary-hero-06/en.json";
import secondaryHero07En from "../components/sections-secondary-hero/secondary-hero-07/en.json";
import secondaryHero08En from "../components/sections-secondary-hero/secondary-hero-08/en.json";
import secondaryHero09En from "../components/sections-secondary-hero/secondary-hero-09/en.json";
import secondaryHero10En from "../components/sections-secondary-hero/secondary-hero-10/en.json";
import secondaryHero11En from "../components/sections-secondary-hero/secondary-hero-11/en.json";
import secondaryHero12En from "../components/sections-secondary-hero/secondary-hero-12/en.json";
import secondaryHero13En from "../components/sections-secondary-hero/secondary-hero-13/en.json";
import secondaryHero14En from "../components/sections-secondary-hero/secondary-hero-14/en.json";
import secondaryHero15En from "../components/sections-secondary-hero/secondary-hero-15/en.json";
import secondaryHero16En from "../components/sections-secondary-hero/secondary-hero-16/en.json";
import secondaryHero17En from "../components/sections-secondary-hero/secondary-hero-17/en.json";
import secondaryHero18En from "../components/sections-secondary-hero/secondary-hero-18/en.json";
import secondaryHero19En from "../components/sections-secondary-hero/secondary-hero-19/en.json";
import secondaryHero20En from "../components/sections-secondary-hero/secondary-hero-20/en.json";
import settingsDialogEn from "../components/sections-modals/settings-dialog/en.json";
import stats01En from "../components/sections-stats/stats-01/en.json";
import stats02En from "../components/sections-stats/stats-02/en.json";
import stats03En from "../components/sections-stats/stats-03/en.json";
import stats04En from "../components/sections-stats/stats-04/en.json";
import stats05En from "../components/sections-stats/stats-05/en.json";
import stats06En from "../components/sections-stats/stats-06/en.json";
import stats07En from "../components/sections-stats/stats-07/en.json";
import stats08En from "../components/sections-stats/stats-08/en.json";
import stats10En from "../components/sections-stats/stats-10/en.json";
import stats11En from "../components/sections-stats/stats-11/en.json";
import stats12En from "../components/sections-stats/stats-12/en.json";
import stats13En from "../components/sections-stats/stats-13/en.json";
import stats14En from "../components/sections-stats/stats-14/en.json";
import stats16En from "../components/sections-stats/stats-16/en.json";
import stats17En from "../components/sections-stats/stats-17/en.json";
import stats18En from "../components/sections-stats/stats-18/en.json";
import stats19En from "../components/sections-stats/stats-19/en.json";
import stats20En from "../components/sections-stats/stats-20/en.json";
import team01En from "../components/sections-team/team-01/en.json";
import team02En from "../components/sections-team/team-02/en.json";
import team03En from "../components/sections-team/team-03/en.json";
import team04En from "../components/sections-team/team-04/en.json";
import team05En from "../components/sections-team/team-05/en.json";
import testimonials01En from "../components/sections-testimonials/testimonials-01/en.json";
import testimonials02En from "../components/sections-testimonials/testimonials-02/en.json";
import testimonials03En from "../components/sections-testimonials/testimonials-03/en.json";
import testimonials04En from "../components/sections-testimonials/testimonials-04/en.json";
import testimonials05En from "../components/sections-testimonials/testimonials-05/en.json";
import testimonials06En from "../components/sections-testimonials/testimonials-06/en.json";
import testimonials07En from "../components/sections-testimonials/testimonials-07/en.json";
import testimonials08En from "../components/sections-testimonials/testimonials-08/en.json";
import testimonials09En from "../components/sections-testimonials/testimonials-09/en.json";
import testimonials10En from "../components/sections-testimonials/testimonials-10/en.json";
import testimonials11En from "../components/sections-testimonials/testimonials-11/en.json";
import testimonials12En from "../components/sections-testimonials/testimonials-12/en.json";
import testimonials13En from "../components/sections-testimonials/testimonials-13/en.json";
import testimonials14En from "../components/sections-testimonials/testimonials-14/en.json";
import timeline01En from "../components/sections-timelines/timeline-01/en.json";
import timeline02En from "../components/sections-timelines/timeline-02/en.json";
import _3dPinEn from "../components/ui-effects/3d-pin.en.json";
import iconCloudEn from "../components/ui-effects/icon-cloud/en.json";
import worldMapEn from "../components/ui-effects/world-map/en.json";
import commandPaletteEn from "../components/ui-effects/command-palette/en.json";
import heroVideoDialogEn from "../components/ui-effects/hero-video-dialog/en.json";
import sidebarTriggerEn from "../components/ui-effects/sidebar-trigger/en.json";
import ditherShaderEn from "../components/ui-effects/dither-shader/en.json";
import pixelatedCanvasEn from "../components/ui-effects/pixelated-canvas/en.json";
import webcamPixelGridEn from "../components/ui-effects/webcam-pixel-grid/en.json";
import animatedTestimonialsEn from "../components/ui-effects/animated-testimonials/en.json";
import tweetNotFoundEn from "../components/ui-effects/tweet-not-found/en.json";
import layoutTextFlipEn from "../components/ui-effects/layout-text-flip/en.json";
import chartAreaAxesEn from "../components/ui-molecules/chart/area/axes/en.json";
import chartAreaDefaultEn from "../components/ui-molecules/chart/area/default/en.json";
import chartAreaGradientEn from "../components/ui-molecules/chart/area/gradient/en.json";
import chartAreaIconsEn from "../components/ui-molecules/chart/area/icons/en.json";
import chartAreaInteractiveEn from "../components/ui-molecules/chart/area/interactive/en.json";
import chartAreaLegendEn from "../components/ui-molecules/chart/area/legend/en.json";
import chartAreaLinearEn from "../components/ui-molecules/chart/area/linear/en.json";
import chartAreaStackedEn from "../components/ui-molecules/chart/area/stacked/en.json";
import chartAreaStackedExpandEn from "../components/ui-molecules/chart/area/stacked-expand/en.json";
import chartAreaStepEn from "../components/ui-molecules/chart/area/step/en.json";
import chartBarActiveEn from "../components/ui-molecules/chart/bar/active/en.json";
import chartBarDefaultEn from "../components/ui-molecules/chart/bar/default/en.json";
import chartBarHorizontalEn from "../components/ui-molecules/chart/bar/horizontal/en.json";
import chartBarInteractiveEn from "../components/ui-molecules/chart/bar/interactive/en.json";
import chartBarLabelCustomEn from "../components/ui-molecules/chart/bar/label-custom/en.json";
import commandMenu01En from "../components/ui-molecules/command-menu/01/en.json";
import commandMenu02En from "../components/ui-molecules/command-menu/02/en.json";
import commandMenu03En from "../components/ui-molecules/command-menu/03/en.json";
import enterpriseFormEn from "../components/ui-molecules/form/contact-enterprise/en.json";
import loginFormEn from "../components/ui-molecules/form/login/en.json";
import signupFormEn from "../components/ui-molecules/form/signup/en.json";
import navCollapseEn from "../components/ui-molecules/nav/collapse/en.json";
import navDocumentsEn from "../components/ui-molecules/nav/documents/en.json";
import navFavoritesEn from "../components/ui-molecules/nav/favorites/en.json";
import navFooterEn from "../components/ui-molecules/nav/footer/en.json";
import navHeaderEn from "../components/ui-molecules/nav/header/en.json";
import navMainFlatEn from "../components/ui-molecules/nav/main/flat/en.json";
import navNotificationsEn from "../components/ui-molecules/nav/notifications/en.json";
import navUserChevronEn from "../components/ui-molecules/nav/user/chevron/en.json";
import navUserDotsEn from "../components/ui-molecules/nav/user/dots/en.json";
import navWorkspacesEn from "../components/ui-molecules/nav/workspaces/en.json";
import pageHeaderEn from "../components/ui-molecules/page-header/en.json";
import teamSwitcherFlatEn from "../components/ui-molecules/team-switcher/flat/en.json";
import teamSwitcherGroupedEn from "../components/ui-molecules/team-switcher/grouped/en.json";
import teamSwitcherToggleEn from "../components/ui-molecules/team-switcher/toggle/en.json";
import sectionCardsEn from "../components/ui-molecules/widget/kpi-cards/en.json";
import stats15En from "../components/ui-molecules/widget/stat-tile/projection/en.json";
import stats09En from "../components/ui-molecules/widget/stat-tile/usage/en.json";
import trendBadgeEn from "../components/ui-molecules/widget/trend-badge/en.json";

/**
 * Story-title → `{ "<block-key>": <en.json> }` map. Used by
 * `.storybook/preview.tsx` to render each story with ONLY its own
 * block's translations in scope (instead of the full ~500-block tree
 * that the app composes at request time). Stories whose folder has no
 * `en.json` are absent from the map — the preview decorator falls back
 * to `loadBlockMessages()` for those (page-templates, layouts, etc.
 * that compose many blocks).
 */
export const STORY_MESSAGES: Record<string, Record<string, unknown>> = {
  "Layouts/Dashboard/Sidebars/Sidebar01": { "sidebar-01": sidebar01En },
  "Layouts/Dashboard/Sidebars/Sidebar02": { "sidebar-02": sidebar02En },
  "Layouts/Dashboard/Sidebars/Sidebar03": { "sidebar-03": sidebar03En },
  "Layouts/Dashboard/Sidebars/Sidebar04": { "sidebar-04": sidebar04En },
  "Layouts/Dashboard/Sidebars/Sidebar05": { "sidebar-05": sidebar05En },
  "Layouts/Dashboard/Sidebars/Sidebar06": { "sidebar-06": sidebar06En },
  "Layouts/Dashboard/Sidebars/Sidebar07": { "sidebar-07": sidebar07En },
  "Layouts/Dashboard/Sidebars/Sidebar08": { "sidebar-08": sidebar08En },
  "Layouts/Dashboard/Sidebars/Sidebar09": { "sidebar-09": sidebar09En },
  "Layouts/Default/SiteFooter": { "site-footer": siteFooterEn },
  "Layouts/Shared/LocaleSwitcher": { "locale-switcher": localeSwitcherEn },
  "Layouts/Shared/SiteFooters/SiteFooter10": { "site-footer-10": siteFooter10En },
  "Layouts/Shared/SiteFooters/SiteFooter11": { "site-footer-11": siteFooter11En },
  "Layouts/Shared/SiteFooters/SiteFooter12": { "site-footer-12": siteFooter12En },
  "Layouts/Shared/SiteFooters/SiteFooter13": { "site-footer-13": siteFooter13En },
  "Layouts/Shared/SiteFooters/SiteFooter2": { "site-footer-2": siteFooter2En },
  "Layouts/Shared/SiteFooters/SiteFooter3": { "site-footer-3": siteFooter3En },
  "Layouts/Shared/SiteFooters/SiteFooter4": { "site-footer-4": siteFooter4En },
  "Layouts/Shared/SiteFooters/SiteFooter5": { "site-footer-5": siteFooter5En },
  "Layouts/Shared/SiteFooters/SiteFooter6": { "site-footer-6": siteFooter6En },
  "Layouts/Shared/SiteFooters/SiteFooter7": { "site-footer-7": siteFooter7En },
  "Layouts/Shared/SiteFooters/SiteFooter8": { "site-footer-8": siteFooter8En },
  "Layouts/Shared/SiteFooters/SiteFooter9": { "site-footer-9": siteFooter9En },
  "Layouts/Shared/SiteHeaders/Header1": { "header-1": header1En },
  "Layouts/Shared/SiteHeaders/Header10": { "header-10": header10En },
  "Layouts/Shared/SiteHeaders/Header2": { "header-2": header2En },
  "Layouts/Shared/SiteHeaders/Header3": { "header-3": header3En },
  "Layouts/Shared/SiteHeaders/Header4": { "header-4": header4En },
  "Layouts/Shared/SiteHeaders/Header5": { "header-5": header5En },
  "Layouts/Shared/SiteHeaders/Header6": { "header-6": header6En },
  "Layouts/Shared/SiteHeaders/Header7": { "header-7": header7En },
  "Layouts/Shared/SiteHeaders/Header8": { "header-8": header8En },
  "Layouts/Shared/SkipLink": { "skip-link": skipLinkEn },
  "Layouts/Shared/ThemeToggle": { "theme-toggle": themeToggleEn },
  "Layouts/Sidebar": { sidebar: sidebarEn },
  "Pages/About/About01": { "about-01": about01En },
  "Pages/About/About02": { "about-02": about02En },
  "Pages/Brand/Brand01": { "brand-01": brand01En },
  "Pages/Contact/ContactPage01": { "contact-page-01": contactPage01En },
  "Pages/Contact/ContactPage02": { "contact-page-02": contactPage02En },
  "Pages/Contact/ContactPage03": { "contact-page-03": contactPage03En },
  "Pages/Contact/ContactPage04": { "contact-page-04": contactPage04En },
  "Pages/Contact/ContactPage05": { "contact-page-05": contactPage05En },
  "Pages/Contact/ContactPage06": { "contact-page-06": contactPage06En },
  "Pages/Customers/Customers01": { "customers-01": customers01En },
  "Pages/Customers/Customers02": { "customers-02": customers02En },
  "Pages/Customers/Customers03": { "customers-03": customers03En },
  "Pages/Customers/Customers04": { "customers-04": customers04En },
  "Pages/CustomerStory/CustomerStory01": { "customer-story-01": customerStory01En },
  "Pages/CustomerStory/CustomerStory02": { "customer-story-02": customerStory02En },
  "Pages/CustomerStory/CustomerStory03": { "customer-story-03": customerStory03En },
  "Pages/CustomerStory/CustomerStory04": { "customer-story-04": customerStory04En },
  "Pages/CustomerStory/CustomerStory05": { "customer-story-05": customerStory05En },
  "Pages/Dashboard/Dashboard01": { "dashboard-01": dashboard01En },
  "Pages/Error/Error01": { "error-01": error01En },
  "Pages/ForgotPassword/ForgotPassword01": { "forgot-password-01": forgotPassword01En },
  "Pages/Landing/Landing01": { "landing-01": landing01En },
  "Pages/Landing/Landing02": { "landing-02": landing02En },
  "Pages/Landing/Landing03": { "landing-03": landing03En },
  "Pages/Landing/Landing04": { "landing-04": landing04En },
  "Pages/Landing/Landing05": { "landing-05": landing05En },
  "Pages/Landing/Landing06": { "landing-06": landing06En },
  "Pages/Login/Login01": { "pages-login-01": pagesLogin01En },
  "Pages/NotFound/NotFound01": { "not-found-01": notFound01En },
  "Pages/Pricing/PricingPage01": { "pricing-page-01": pricingPage01En },
  "Pages/Pricing/PricingPage02": { "pricing-page-02": pricingPage02En },
  "Pages/Pricing/PricingPage03": { "pricing-page-03": pricingPage03En },
  "Pages/Pricing/PricingPage04": { "pricing-page-04": pricingPage04En },
  "Pages/Pricing/PricingPage05": { "pricing-page-05": pricingPage05En },
  "Pages/Product/Product01": { "product-01": product01En },
  "Pages/Product/Product02": { "product-02": product02En },
  "Pages/Signup/Signup01": { "signup-01": signup01En },
  "Pages/Solutions/Solutions01": { "solutions-01": solutions01En },
  "Sections/Ai/Ai01": { "ai-01": ai01En },
  "Sections/Ai/Ai02": { "ai-02": ai02En },
  "Sections/Ai/Ai03": { "ai-03": ai03En },
  "Sections/Ai/Ai04": { "ai-04": ai04En },
  "Sections/Ai/Ai05": { "ai-05": ai05En },
  "Sections/Auth/ForgotPassword": { "forgot-password": forgotPasswordEn },
  "Sections/Auth/ForgotPassword02": { "forgot-password-02": forgotPassword02En },
  "Sections/Auth/ForgotPassword03": { "forgot-password-03": forgotPassword03En },
  "Sections/Auth/ForgotPassword04": { "forgot-password-04": forgotPassword04En },
  "Sections/Auth/ForgotPassword05": { "forgot-password-05": forgotPassword05En },
  "Sections/Auth/Login01": { "login-01": login01En },
  "Sections/Auth/Login02": { "login-02": login02En },
  "Sections/Auth/Login03": { "login-03": login03En },
  "Sections/Auth/Login04": { "login-04": login04En },
  "Sections/Auth/Login05": { "login-05": login05En },
  "Sections/Auth/Login06": { "login-06": login06En },
  "Sections/Auth/Login07": { "login-07": login07En },
  "Sections/Auth/Login08": { "login-08": login08En },
  "Sections/Auth/Login09": { "login-09": login09En },
  "Sections/Auth/Login10": { "login-10": login10En },
  "Sections/Auth/Login11": { "login-11": login11En },
  "Sections/Auth/Login12": { "login-12": login12En },
  "Sections/Auth/Login13": { "login-13": login13En },
  "Sections/Auth/Login14": { "login-14": login14En },
  "Sections/Auth/Login15": { "login-15": login15En },
  "Sections/Auth/Login16": { "login-16": login16En },
  "Sections/Auth/Login17": { "login-17": login17En },
  "Sections/Auth/Login18": { "login-18": login18En },
  "Sections/Auth/Login19": { "login-19": login19En },
  "Sections/Auth/Login20": { "login-20": login20En },
  "Sections/Auth/Login21": { "login-21": login21En },
  "Sections/Auth/Login22": { "login-22": login22En },
  "Sections/Auth/Login23": { "login-23": login23En },
  "Sections/Bento/Bento01": { "bento-01": bento01En },
  "Sections/Bento/Bento02": { "bento-02": bento02En },
  "Sections/Bento/Bento03": { "bento-03": bento03En },
  "Sections/Bento/Bento04": { "bento-04": bento04En },
  "Sections/Bento/Bento05": { "bento-05": bento05En },
  "Sections/Bento/Bento06": { "bento-06": bento06En },
  "Sections/Bento/Bento07": { "bento-07": bento07En },
  "Sections/Bento/Bento08": { "bento-08": bento08En },
  "Sections/Bento/Bento09": { "bento-09": bento09En },
  "Sections/Bento/Bento10": { "bento-10": bento10En },
  "Sections/Bento/Bento11": { "bento-11": bento11En },
  "Sections/Bento/Bento12": { "bento-12": bento12En },
  "Sections/Bento/Bento13": { "bento-13": bento13En },
  "Sections/Bento/Bento14": { "bento-14": bento14En },
  "Sections/CodeDemo/CodeDemo01": { "code-demo-01": codeDemo01En },
  "Sections/CodeDemo/CodeDemo02": { "code-demo-02": codeDemo02En },
  "Sections/CodeDemo/CodeDemo03": { "code-demo-03": codeDemo03En },
  "Sections/CodeDemo/CodeDemo04": { "code-demo-04": codeDemo04En },
  "Sections/Contact/Contact01": { "contact-01": contact01En },
  "Sections/Content/Content01": { "content-01": content01En },
  "Sections/Content/Content02": { "content-02": content02En },
  "Sections/Content/Content03": { "content-03": content03En },
  "Sections/Content/Content04": { "content-04": content04En },
  "Sections/Content/Content05": { "content-05": content05En },
  "Sections/Content/Content06": { "content-06": content06En },
  "Sections/Content/Content07": { "content-07": content07En },
  "Sections/Content/Content08": { "content-08": content08En },
  "Sections/Content/Content09": { "content-09": content09En },
  "Sections/Content/Content10": { "content-10": content10En },
  "Sections/Content/Content11": { "content-11": content11En },
  "Sections/Content/Content12": { "content-12": content12En },
  "Sections/Content/Content13": { "content-13": content13En },
  "Sections/Content/Content14": { "content-14": content14En },
  "Sections/Content/Content15": { "content-15": content15En },
  "Sections/Content/Content16": { "content-16": content16En },
  "Sections/Content/Content17": { "content-17": content17En },
  "Sections/Content/Content18": { "content-18": content18En },
  "Sections/Content/Content19": { "content-19": content19En },
  "Sections/Content/Content20": { "content-20": content20En },
  "Sections/Content/Content21": { "content-21": content21En },
  "Sections/Content/Content22": { "content-22": content22En },
  "Sections/Content/Content23": { "content-23": content23En },
  "Sections/Content/Content24": { "content-24": content24En },
  "Sections/Content/Content25": { "content-25": content25En },
  "Sections/Content/Content26": { "content-26": content26En },
  "Sections/Content/Content27": { "content-27": content27En },
  "Sections/Content/Content28": { "content-28": content28En },
  "Sections/Content/Content29": { "content-29": content29En },
  "Sections/Content/Content30": { "content-30": content30En },
  "Sections/Content/Content31": { "content-31": content31En },
  "Sections/Content/Content32": { "content-32": content32En },
  "Sections/Cta/Cta01": { "cta-01": cta01En },
  "Sections/Cta/Cta02": { "cta-02": cta02En },
  "Sections/Cta/Cta03": { "cta-03": cta03En },
  "Sections/Cta/Cta04": { "cta-04": cta04En },
  "Sections/Cta/Cta05": { "cta-05": cta05En },
  "Sections/Cta/Cta06": { "cta-06": cta06En },
  "Sections/Cta/Cta07": { "cta-07": cta07En },
  "Sections/Cta/Cta08": { "cta-08": cta08En },
  "Sections/Cta/Cta09": { "cta-09": cta09En },
  "Sections/Cta/Cta10": { "cta-10": cta10En },
  "Sections/Cta/Cta11": { "cta-11": cta11En },
  "Sections/Cta/Cta12": { "cta-12": cta12En },
  "Sections/Dashboard/QuickActions01": { "quick-actions-01": quickActions01En },
  "Sections/Dashboard/RecentActivity01": { "recent-activity-01": recentActivity01En },
  "Sections/Dashboard/WelcomeBanner01": { "welcome-banner-01": welcomeBanner01En },
  "Sections/Data/DataTable": { "data-table": dataTableEn },
  "Sections/Data/Table01": { "table-01": table01En },
  "Sections/Data/Table02": { "table-02": table02En },
  "Sections/Data/Table03": { "table-03": table03En },
  "Sections/Data/Table04": { "table-04": table04En },
  "Sections/Data/Table05": { "table-05": table05En },
  "Sections/Faq/Faq01": { "faq-01": faq01En },
  "Sections/Faq/Faq02": { "faq-02": faq02En },
  "Sections/Faq/Faq03": { "faq-03": faq03En },
  "Sections/Faq/Faq04": { "faq-04": faq04En },
  "Sections/Faq/Faq05": { "faq-05": faq05En },
  "Sections/Faq/Faq06": { "faq-06": faq06En },
  "Sections/Faq/Faq07": { "faq-07": faq07En },
  "Sections/Faq/Faq08": { "faq-08": faq08En },
  "Sections/Faq/Faq09": { "faq-09": faq09En },
  "Sections/Faq/Faq10": { "faq-10": faq10En },
  "Sections/Faq/Faq11": { "faq-11": faq11En },
  "Sections/Faq/Faq12": { "faq-12": faq12En },
  "Sections/Features/Features01": { "features-01": features01En },
  "Sections/Features/Features02": { "features-02": features02En },
  "Sections/Features/Features03": { "features-03": features03En },
  "Sections/Features/Features04": { "features-04": features04En },
  "Sections/Features/Features05": { "features-05": features05En },
  "Sections/Features/Features06": { "features-06": features06En },
  "Sections/Features/Features07": { "features-07": features07En },
  "Sections/Features/Features08": { "features-08": features08En },
  "Sections/Features/Features09": { "features-09": features09En },
  "Sections/Features/Features10": { "features-10": features10En },
  "Sections/Features/Features11": { "features-11": features11En },
  "Sections/Features/Features12": { "features-12": features12En },
  "Sections/Features/Features13": { "features-13": features13En },
  "Sections/Features/Features14": { "features-14": features14En },
  "Sections/Features/Features15": { "features-15": features15En },
  "Sections/Features/Features16": { "features-16": features16En },
  "Sections/Features/Features17": { "features-17": features17En },
  "Sections/Features/Features18": { "features-18": features18En },
  "Sections/Features/Features19": { "features-19": features19En },
  "Sections/Features/Features20": { "features-20": features20En },
  "Sections/Features/Features21": { "features-21": features21En },
  "Sections/Features/Features22": { "features-22": features22En },
  "Sections/Features/Features23": { "features-23": features23En },
  "Sections/Features/Features24": { "features-24": features24En },
  "Sections/Features/Features25": { "features-25": features25En },
  "Sections/Features/Features26": { "features-26": features26En },
  "Sections/Features/Features27": { "features-27": features27En },
  "Sections/Features/Features28": { "features-28": features28En },
  "Sections/Features/Features29": { "features-29": features29En },
  "Sections/Features/Features30": { "features-30": features30En },
  "Sections/Features/Features31": { "features-31": features31En },
  "Sections/Features/Features32": { "features-32": features32En },
  "Sections/Features/Features33": { "features-33": features33En },
  "Sections/Features/Features34": { "features-34": features34En },
  "Sections/Features/Features35": { "features-35": features35En },
  "Sections/Features/Features36": { "features-36": features36En },
  "Sections/Features/Features37": { "features-37": features37En },
  "Sections/Features/Features38": { "features-38": features38En },
  "Sections/Features/Features39": { "features-39": features39En },
  "Sections/Features/Features40": { "features-40": features40En },
  "Sections/Features/Features41": { "features-41": features41En },
  "Sections/Features/Features42": { "features-42": features42En },
  "Sections/Features/Features43": { "features-43": features43En },
  "Sections/FeaturesCarousel/FeaturesCarousel01": {
    "features-carousel-01": featuresCarousel01En,
  },
  "Sections/FeaturesCarousel/FeaturesCarousel02": {
    "features-carousel-02": featuresCarousel02En,
  },
  "Sections/FeaturesCarousel/FeaturesCarousel03": {
    "features-carousel-03": featuresCarousel03En,
  },
  "Sections/FeaturesCarousel/FeaturesCarousel04": {
    "features-carousel-04": featuresCarousel04En,
  },
  "Sections/FeaturesCarousel/FeaturesCarousel05": {
    "features-carousel-05": featuresCarousel05En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable01": {
    "features-expandable-01": featuresExpandable01En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable02": {
    "features-expandable-02": featuresExpandable02En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable03": {
    "features-expandable-03": featuresExpandable03En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable04": {
    "features-expandable-04": featuresExpandable04En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable05": {
    "features-expandable-05": featuresExpandable05En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable06": {
    "features-expandable-06": featuresExpandable06En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable07": {
    "features-expandable-07": featuresExpandable07En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable08": {
    "features-expandable-08": featuresExpandable08En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable09": {
    "features-expandable-09": featuresExpandable09En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable10": {
    "features-expandable-10": featuresExpandable10En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable11": {
    "features-expandable-11": featuresExpandable11En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable12": {
    "features-expandable-12": featuresExpandable12En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable13": {
    "features-expandable-13": featuresExpandable13En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable14": {
    "features-expandable-14": featuresExpandable14En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable15": {
    "features-expandable-15": featuresExpandable15En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable16": {
    "features-expandable-16": featuresExpandable16En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable17": {
    "features-expandable-17": featuresExpandable17En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable18": {
    "features-expandable-18": featuresExpandable18En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable19": {
    "features-expandable-19": featuresExpandable19En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable20": {
    "features-expandable-20": featuresExpandable20En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable21": {
    "features-expandable-21": featuresExpandable21En,
  },
  "Sections/FeaturesExpandable/FeaturesExpandable22": {
    "features-expandable-22": featuresExpandable22En,
  },
  "Sections/FileUpload/FileUpload01": { "file-upload-01": fileUpload01En },
  "Sections/FileUpload/FileUpload02": { "file-upload-02": fileUpload02En },
  "Sections/FileUpload/FileUpload03": { "file-upload-03": fileUpload03En },
  "Sections/FileUpload/FileUpload04": { "file-upload-04": fileUpload04En },
  "Sections/FileUpload/FileUpload05": { "file-upload-05": fileUpload05En },
  "Sections/FileUpload/FileUpload06": { "file-upload-06": fileUpload06En },
  "Sections/Form/FormLayout01": { "form-layout-01": formLayout01En },
  "Sections/Form/FormLayout02": { "form-layout-02": formLayout02En },
  "Sections/Form/FormLayout03": { "form-layout-03": formLayout03En },
  "Sections/Form/FormLayout04": { "form-layout-04": formLayout04En },
  "Sections/Form/FormLayout05": { "form-layout-05": formLayout05En },
  "Sections/Hero/Hero01": { "hero-01": hero01En },
  "Sections/Hero/Hero02": { "hero-02": hero02En },
  "Sections/Hero/Hero03": { "hero-03": hero03En },
  "Sections/Hero/Hero04": { "hero-04": hero04En },
  "Sections/Hero/Hero05": { "hero-05": hero05En },
  "Sections/Hero/Hero06": { "hero-06": hero06En },
  "Sections/Hero/Hero07": { "hero-07": hero07En },
  "Sections/Hero/Hero08": { "hero-08": hero08En },
  "Sections/Hero/Hero09": { "hero-09": hero09En },
  "Sections/Hero/Hero10": { "hero-10": hero10En },
  "Sections/Hero/Hero11": { "hero-11": hero11En },
  "Sections/Hero/Hero12": { "hero-12": hero12En },
  "Sections/Hero/Hero13": { "hero-13": hero13En },
  "Sections/Hero/Hero14": { "hero-14": hero14En },
  "Sections/Hero/Hero15": { "hero-15": hero15En },
  "Sections/Hero/Hero16": { "hero-16": hero16En },
  "Sections/Hero/Hero17": { "hero-17": hero17En },
  "Sections/Hero/Hero18": { "hero-18": hero18En },
  "Sections/Hero/Hero19": { "hero-19": hero19En },
  "Sections/Hero/Hero20": { "hero-20": hero20En },
  "Sections/Hero/Hero21": { "hero-21": hero21En },
  "Sections/Hero/Hero22": { "hero-22": hero22En },
  "Sections/Hero/Hero23": { "hero-23": hero23En },
  "Sections/Hero/Hero24": { "hero-24": hero24En },
  "Sections/Hero/Hero25": { "hero-25": hero25En },
  "Sections/HowItWorks/HowItWorks01": { "how-it-works-01": howItWorks01En },
  "Sections/HowItWorks/HowItWorks02": { "how-it-works-02": howItWorks02En },
  "Sections/HowItWorks/HowItWorks03": { "how-it-works-03": howItWorks03En },
  "Sections/HowItWorks/HowItWorks04": { "how-it-works-04": howItWorks04En },
  "Sections/HowItWorks/HowItWorks05": { "how-it-works-05": howItWorks05En },
  "Sections/HowItWorks/HowItWorks06": { "how-it-works-06": howItWorks06En },
  "Sections/HowItWorks/HowItWorks07": { "how-it-works-07": howItWorks07En },
  "Sections/HowItWorks/HowItWorks08": { "how-it-works-08": howItWorks08En },
  "Sections/HowItWorks/HowItWorks09": { "how-it-works-09": howItWorks09En },
  "Sections/Integrations/Integrations01": { "integrations-01": integrations01En },
  "Sections/Integrations/Integrations02": { "integrations-02": integrations02En },
  "Sections/Integrations/Integrations05": { "integrations-05": integrations05En },
  "Sections/Integrations/Integrations06": { "integrations-06": integrations06En },
  "Sections/Integrations/Integrations07": { "integrations-07": integrations07En },
  "Sections/Integrations/Integrations09": { "integrations-09": integrations09En },
  "Sections/Integrations/Integrations10": { "integrations-10": integrations10En },
  "Sections/Integrations/Integrations11": { "integrations-11": integrations11En },
  "Sections/Integrations/Integrations12": { "integrations-12": integrations12En },
  "Sections/Integrations/Integrations13": { "integrations-13": integrations13En },
  "Sections/Integrations/Integrations14": { "integrations-14": integrations14En },
  "Sections/Integrations/Integrations15": { "integrations-15": integrations15En },
  "Sections/Integrations/Integrations16": { "integrations-16": integrations16En },
  "Sections/Integrations/Integrations17": { "integrations-17": integrations17En },
  "Sections/Integrations/Integrations18": { "integrations-18": integrations18En },
  "Sections/Lists/GridList01": { "grid-list-01": gridList01En },
  "Sections/Lists/GridList02": { "grid-list-02": gridList02En },
  "Sections/Lists/GridList03": { "grid-list-03": gridList03En },
  "Sections/LogoCloud/LogoCloud01": { "logo-cloud-01": logoCloud01En },
  "Sections/LogoCloud/LogoCloud02": { "logo-cloud-02": logoCloud02En },
  "Sections/LogoCloud/LogoCloud03": { "logo-cloud-03": logoCloud03En },
  "Sections/LogoCloud/LogoCloud04": { "logo-cloud-04": logoCloud04En },
  "Sections/LogoCloud/LogoCloud05": { "logo-cloud-05": logoCloud05En },
  "Sections/LogoCloud/LogoCloud06": { "logo-cloud-06": logoCloud06En },
  "Sections/LogoCloud/LogoCloud07": { "logo-cloud-07": logoCloud07En },
  "Sections/LogoCloud/LogoCloud08": { "logo-cloud-08": logoCloud08En },
  "Sections/LogoCloud/LogoCloud09": { "logo-cloud-09": logoCloud09En },
  "Sections/LogoCloud/LogoCloud10": { "logo-cloud-10": logoCloud10En },
  "Sections/LogoCloud/LogoCloud11": { "logo-cloud-11": logoCloud11En },
  "Sections/LogoCloud/LogoCloud12": { "logo-cloud-12": logoCloud12En },
  "Sections/LogoCloud/LogoCloud13": { "logo-cloud-13": logoCloud13En },
  "Sections/LogoCloud/LogoCloud14": { "logo-cloud-14": logoCloud14En },
  "Sections/LogoCloud/LogoCloud15": { "logo-cloud-15": logoCloud15En },
  "Sections/Modals/Dialog01": { "dialog-01": dialog01En },
  "Sections/Modals/Dialog02": { "dialog-02": dialog02En },
  "Sections/Modals/Dialog03": { "dialog-03": dialog03En },
  "Sections/Modals/Dialog04": { "dialog-04": dialog04En },
  "Sections/Modals/Dialog05": { "dialog-05": dialog05En },
  "Sections/Modals/Dialog06": { "dialog-06": dialog06En },
  "Sections/Modals/Dialog07": { "dialog-07": dialog07En },
  "Sections/Modals/Dialog08": { "dialog-08": dialog08En },
  "Sections/Modals/Dialog09": { "dialog-09": dialog09En },
  "Sections/Modals/Dialog10": { "dialog-10": dialog10En },
  "Sections/Modals/Dialog11": { "dialog-11": dialog11En },
  "Sections/Modals/Dialog12": { "dialog-12": dialog12En },
  "Sections/Onboarding/Onboarding01": { "onboarding-01": onboarding01En },
  "Sections/Onboarding/Onboarding02": { "onboarding-02": onboarding02En },
  "Sections/Onboarding/Onboarding03": { "onboarding-03": onboarding03En },
  "Sections/Onboarding/Onboarding04": { "onboarding-04": onboarding04En },
  "Sections/Onboarding/Onboarding07": { "onboarding-07": onboarding07En },
  "Sections/Pricing/Pricing01": { "pricing-01": pricing01En },
  "Sections/Pricing/Pricing02": { "pricing-02": pricing02En },
  "Sections/Pricing/Pricing03": { "pricing-03": pricing03En },
  "Sections/Pricing/Pricing04": { "pricing-04": pricing04En },
  "Sections/Pricing/Pricing05": { "pricing-05": pricing05En },
  "Sections/Pricing/Pricing06": { "pricing-06": pricing06En },
  "Sections/Pricing/Pricing07": { "pricing-07": pricing07En },
  "Sections/Pricing/Pricing08": { "pricing-08": pricing08En },
  "Sections/Pricing/Pricing09": { "pricing-09": pricing09En },
  "Sections/Pricing/PricingComparator": { "pricing-comparator": pricingComparatorEn },
  "Sections/Pricing/PricingComparator02": {
    "pricing-comparator-02": pricingComparator02En,
  },
  "Sections/Pricing/PricingComparator03": {
    "pricing-comparator-03": pricingComparator03En,
  },
  "Sections/Pricing/PricingComparator04": {
    "pricing-comparator-04": pricingComparator04En,
  },
  "Sections/SecondaryHero/SecondaryHero01": { "secondary-hero-01": secondaryHero01En },
  "Sections/SecondaryHero/SecondaryHero02": { "secondary-hero-02": secondaryHero02En },
  "Sections/SecondaryHero/SecondaryHero03": { "secondary-hero-03": secondaryHero03En },
  "Sections/SecondaryHero/SecondaryHero04": { "secondary-hero-04": secondaryHero04En },
  "Sections/SecondaryHero/SecondaryHero05": { "secondary-hero-05": secondaryHero05En },
  "Sections/SecondaryHero/SecondaryHero06": { "secondary-hero-06": secondaryHero06En },
  "Sections/SecondaryHero/SecondaryHero07": { "secondary-hero-07": secondaryHero07En },
  "Sections/SecondaryHero/SecondaryHero08": { "secondary-hero-08": secondaryHero08En },
  "Sections/SecondaryHero/SecondaryHero09": { "secondary-hero-09": secondaryHero09En },
  "Sections/SecondaryHero/SecondaryHero10": { "secondary-hero-10": secondaryHero10En },
  "Sections/SecondaryHero/SecondaryHero11": { "secondary-hero-11": secondaryHero11En },
  "Sections/SecondaryHero/SecondaryHero12": { "secondary-hero-12": secondaryHero12En },
  "Sections/SecondaryHero/SecondaryHero13": { "secondary-hero-13": secondaryHero13En },
  "Sections/SecondaryHero/SecondaryHero14": { "secondary-hero-14": secondaryHero14En },
  "Sections/SecondaryHero/SecondaryHero15": { "secondary-hero-15": secondaryHero15En },
  "Sections/SecondaryHero/SecondaryHero16": { "secondary-hero-16": secondaryHero16En },
  "Sections/SecondaryHero/SecondaryHero17": { "secondary-hero-17": secondaryHero17En },
  "Sections/SecondaryHero/SecondaryHero18": { "secondary-hero-18": secondaryHero18En },
  "Sections/SecondaryHero/SecondaryHero19": { "secondary-hero-19": secondaryHero19En },
  "Sections/SecondaryHero/SecondaryHero20": { "secondary-hero-20": secondaryHero20En },
  "Sections/Settings/SettingsDialog": { "settings-dialog": settingsDialogEn },
  "Sections/Stats/Stats01": { "stats-01": stats01En },
  "Sections/Stats/Stats02": { "stats-02": stats02En },
  "Sections/Stats/Stats03": { "stats-03": stats03En },
  "Sections/Stats/Stats04": { "stats-04": stats04En },
  "Sections/Stats/Stats05": { "stats-05": stats05En },
  "Sections/Stats/Stats06": { "stats-06": stats06En },
  "Sections/Stats/Stats07": { "stats-07": stats07En },
  "Sections/Stats/Stats08": { "stats-08": stats08En },
  "Sections/Stats/Stats10": { "stats-10": stats10En },
  "Sections/Stats/Stats11": { "stats-11": stats11En },
  "Sections/Stats/Stats12": { "stats-12": stats12En },
  "Sections/Stats/Stats13": { "stats-13": stats13En },
  "Sections/Stats/Stats14": { "stats-14": stats14En },
  "Sections/Stats/Stats16": { "stats-16": stats16En },
  "Sections/Stats/Stats17": { "stats-17": stats17En },
  "Sections/Stats/Stats18": { "stats-18": stats18En },
  "Sections/Stats/Stats19": { "stats-19": stats19En },
  "Sections/Stats/Stats20": { "stats-20": stats20En },
  "Sections/Team/Team01": { "team-01": team01En },
  "Sections/Team/Team02": { "team-02": team02En },
  "Sections/Team/Team03": { "team-03": team03En },
  "Sections/Team/Team04": { "team-04": team04En },
  "Sections/Team/Team05": { "team-05": team05En },
  "Sections/Testimonials/Testimonials01": { "testimonials-01": testimonials01En },
  "Sections/Testimonials/Testimonials02": { "testimonials-02": testimonials02En },
  "Sections/Testimonials/Testimonials03": { "testimonials-03": testimonials03En },
  "Sections/Testimonials/Testimonials04": { "testimonials-04": testimonials04En },
  "Sections/Testimonials/Testimonials05": { "testimonials-05": testimonials05En },
  "Sections/Testimonials/Testimonials06": { "testimonials-06": testimonials06En },
  "Sections/Testimonials/Testimonials07": { "testimonials-07": testimonials07En },
  "Sections/Testimonials/Testimonials08": { "testimonials-08": testimonials08En },
  "Sections/Testimonials/Testimonials09": { "testimonials-09": testimonials09En },
  "Sections/Testimonials/Testimonials10": { "testimonials-10": testimonials10En },
  "Sections/Testimonials/Testimonials11": { "testimonials-11": testimonials11En },
  "Sections/Testimonials/Testimonials12": { "testimonials-12": testimonials12En },
  "Sections/Testimonials/Testimonials13": { "testimonials-13": testimonials13En },
  "Sections/Testimonials/Testimonials14": { "testimonials-14": testimonials14En },
  "Sections/Timelines/Timeline01": { "timeline-01": timeline01En },
  "Sections/Timelines/Timeline02": { "timeline-02": timeline02En },
  "UI Effects/3D & Devices/3dPin": { "3d-pin": _3dPinEn },
  "UI Effects/Globes & Maps/IconCloud": { "icon-cloud": iconCloudEn },
  "UI Effects/Globes & Maps/WorldMap": { "world-map": worldMapEn },
  "UI Effects/Inputs/CommandPalette": { "command-palette": commandPaletteEn },
  "UI Effects/Modals & Overlays/HeroVideoDialog": {
    "hero-video-dialog": heroVideoDialogEn,
  },
  "UI Effects/Nav/SidebarTrigger": { "sidebar-trigger": sidebarTriggerEn },
  "UI Effects/Particles & Effects/DitherShader": { "dither-shader": ditherShaderEn },
  "UI Effects/Particles & Effects/PixelatedCanvas": {
    "pixelated-canvas": pixelatedCanvasEn,
  },
  "UI Effects/Particles & Effects/WebcamPixelGrid": {
    "webcam-pixel-grid": webcamPixelGridEn,
  },
  "UI Effects/Social/AnimatedTestimonials": {
    "animated-testimonials": animatedTestimonialsEn,
  },
  "UI Effects/Social/TweetNotFound": { "tweet-not-found": tweetNotFoundEn },
  "UI Effects/Text/LayoutTextFlip": { "layout-text-flip": layoutTextFlipEn },
  "UI Molecules/Chart/Area/Axes": { "chart-area-axes": chartAreaAxesEn },
  "UI Molecules/Chart/Area/Default": { "chart-area-default": chartAreaDefaultEn },
  "UI Molecules/Chart/Area/Gradient": { "chart-area-gradient": chartAreaGradientEn },
  "UI Molecules/Chart/Area/Icons": { "chart-area-icons": chartAreaIconsEn },
  "UI Molecules/Chart/Area/Interactive": {
    "chart-area-interactive": chartAreaInteractiveEn,
  },
  "UI Molecules/Chart/Area/Legend": { "chart-area-legend": chartAreaLegendEn },
  "UI Molecules/Chart/Area/Linear": { "chart-area-linear": chartAreaLinearEn },
  "UI Molecules/Chart/Area/Stacked": { "chart-area-stacked": chartAreaStackedEn },
  "UI Molecules/Chart/Area/StackedExpand": {
    "chart-area-stacked-expand": chartAreaStackedExpandEn,
  },
  "UI Molecules/Chart/Area/Step": { "chart-area-step": chartAreaStepEn },
  "UI Molecules/Chart/Bar/Active": { "chart-bar-active": chartBarActiveEn },
  "UI Molecules/Chart/Bar/Default": { "chart-bar-default": chartBarDefaultEn },
  "UI Molecules/Chart/Bar/Horizontal": { "chart-bar-horizontal": chartBarHorizontalEn },
  "UI Molecules/Chart/Bar/Interactive": {
    "chart-bar-interactive": chartBarInteractiveEn,
  },
  "UI Molecules/Chart/Bar/LabelCustom": {
    "chart-bar-label-custom": chartBarLabelCustomEn,
  },
  "UI Molecules/CommandMenu/CommandMenu01": { "command-menu-01": commandMenu01En },
  "UI Molecules/CommandMenu/CommandMenu02": { "command-menu-02": commandMenu02En },
  "UI Molecules/CommandMenu/CommandMenu03": { "command-menu-03": commandMenu03En },
  "UI Molecules/Form/ContactEnterprise": { "enterprise-form": enterpriseFormEn },
  "UI Molecules/Form/Login": { "login-form": loginFormEn },
  "UI Molecules/Form/Signup": { "signup-form": signupFormEn },
  "UI Molecules/Nav/Collapse": { "nav-collapse": navCollapseEn },
  "UI Molecules/Nav/Documents": { "nav-documents": navDocumentsEn },
  "UI Molecules/Nav/Favorites": { "nav-favorites": navFavoritesEn },
  "UI Molecules/Nav/Footer": { "nav-footer": navFooterEn },
  "UI Molecules/Nav/Header": { "nav-header": navHeaderEn },
  "UI Molecules/Nav/Main/Flat": { "nav-main-flat": navMainFlatEn },
  "UI Molecules/Nav/Notifications": { "nav-notifications": navNotificationsEn },
  "UI Molecules/Nav/User/Chevron": { "nav-user-chevron": navUserChevronEn },
  "UI Molecules/Nav/User/Dots": { "nav-user-dots": navUserDotsEn },
  "UI Molecules/Nav/Workspaces": { "nav-workspaces": navWorkspacesEn },
  "UI Molecules/PageHeader": { "page-header": pageHeaderEn },
  "UI Molecules/TeamSwitcher/Flat": { "team-switcher-flat": teamSwitcherFlatEn },
  "UI Molecules/TeamSwitcher/Grouped": { "team-switcher-grouped": teamSwitcherGroupedEn },
  "UI Molecules/TeamSwitcher/Toggle": { "team-switcher-toggle": teamSwitcherToggleEn },
  "UI Molecules/Widget/KpiCards": { "section-cards": sectionCardsEn },
  "UI Molecules/Widget/StatTile/Projection": { "stats-15": stats15En },
  "UI Molecules/Widget/StatTile/Usage": { "stats-09": stats09En },
  "UI Molecules/Widget/TrendBadge": { "trend-badge": trendBadgeEn },
};
