// GENERATED by `pnpm --filter @indiecrafts/web-surfaces-website version` (runs inside build:cf). Do not edit.
// Committed placeholder — real values are stamped at build time.
export const buildInfo = {
  version: "0.0.0",
  branch: "local",
  commit: "dev",
  buildTime: "",
} as const;
