// AUTO-GENERATED by scripts/generate-i18n-registry.mjs
// DO NOT EDIT — run `pnpm gen:i18n` to regenerate. Drift caught by `pnpm verify:i18n`.

import type globalEn from "../../messages/en.json";

// ── per-page route messages (hand-maintained — co-located with each route) ──
import type homeEn from "@/app/[locale]/messages/en.json";
import type aboutEn from "@/app/[locale]/about/messages/en.json";

// ── per-block / per-template messages (auto-discovered) ─────────────
import type _3dPinEn from "@/components/ui-effects/3d-pin.en.json";
import type about1En from "@/components/pages-marketing/about-1/en.json";
import type animatedTestimonialsEn from "@/components/ui-effects/AnimatedTestimonials/en.json";
import type appSidebarEn from "@/components/layouts/DashboardLayout/sidebars/AppSidebar/en.json";
import type chartAreaAxesEn from "@/components/sections-app-charts/ChartAreaAxes/en.json";
import type chartAreaDefaultEn from "@/components/sections-app-charts/ChartAreaDefault/en.json";
import type chartAreaGradientEn from "@/components/sections-app-charts/ChartAreaGradient/en.json";
import type chartAreaIconsEn from "@/components/sections-app-charts/ChartAreaIcons/en.json";
import type chartAreaInteractiveEn from "@/components/sections-app-charts/ChartAreaInteractive/en.json";
import type chartAreaLegendEn from "@/components/sections-app-charts/ChartAreaLegend/en.json";
import type chartAreaLinearEn from "@/components/sections-app-charts/ChartAreaLinear/en.json";
import type chartAreaStackedEn from "@/components/sections-app-charts/ChartAreaStacked/en.json";
import type chartAreaStackedExpandEn from "@/components/sections-app-charts/ChartAreaStackedExpand/en.json";
import type chartAreaStepEn from "@/components/sections-app-charts/ChartAreaStep/en.json";
import type chartBarActiveEn from "@/components/sections-app-charts/ChartBarActive/en.json";
import type chartBarDefaultEn from "@/components/sections-app-charts/ChartBarDefault/en.json";
import type chartBarHorizontalEn from "@/components/sections-app-charts/ChartBarHorizontal/en.json";
import type chartBarInteractiveEn from "@/components/sections-app-charts/ChartBarInteractive/en.json";
import type chartBarLabelCustomEn from "@/components/sections-app-charts/ChartBarLabelCustom/en.json";
import type commandPaletteEn from "@/components/ui-effects/CommandPalette/en.json";
import type contact1En from "@/components/sections-marketing-contact/contact-1/en.json";
import type content1En from "@/components/sections-marketing-content/content-1/en.json";
import type content2En from "@/components/sections-marketing-content/content-2/en.json";
import type content3En from "@/components/sections-marketing-content/content-3/en.json";
import type content4En from "@/components/sections-marketing-content/content-4/en.json";
import type content5En from "@/components/sections-marketing-content/content-5/en.json";
import type content6En from "@/components/sections-marketing-content/content-6/en.json";
import type content7En from "@/components/sections-marketing-content/content-7/en.json";
import type cta1En from "@/components/sections-marketing-cta/cta-1/en.json";
import type dashboard1En from "@/components/pages-app/dashboard-1/en.json";
import type dashboardHeaderEn from "@/components/layouts/DashboardLayout/DashboardHeader/en.json";
import type dataTableEn from "@/components/sections-app-data/DataTable/en.json";
import type ditherShaderEn from "@/components/ui-effects/DitherShader/en.json";
import type error1En from "@/components/pages-error/error-1/en.json";
import type faq1En from "@/components/sections-marketing-faq/faq-1/en.json";
import type faq2En from "@/components/sections-marketing-faq/faq-2/en.json";
import type faq3En from "@/components/sections-marketing-faq/faq-3/en.json";
import type faq4En from "@/components/sections-marketing-faq/faq-4/en.json";
import type features1En from "@/components/sections-marketing-features/features-1/en.json";
import type features10En from "@/components/sections-marketing-features/features-10/en.json";
import type features11En from "@/components/sections-marketing-features/features-11/en.json";
import type features12En from "@/components/sections-marketing-features/features-12/en.json";
import type features2En from "@/components/sections-marketing-features/features-2/en.json";
import type features3En from "@/components/sections-marketing-features/features-3/en.json";
import type features4En from "@/components/sections-marketing-features/features-4/en.json";
import type features5En from "@/components/sections-marketing-features/features-5/en.json";
import type features6En from "@/components/sections-marketing-features/features-6/en.json";
import type features7En from "@/components/sections-marketing-features/features-7/en.json";
import type features8En from "@/components/sections-marketing-features/features-8/en.json";
import type features9En from "@/components/sections-marketing-features/features-9/en.json";
import type footer1En from "@/components/sections-marketing-footer/footer-1/en.json";
import type forgotPasswordEn from "@/components/sections-auth/ForgotPassword/en.json";
import type forgotPassword1En from "@/components/pages-auth/forgot-password-1/en.json";
import type heroVideoDialogEn from "@/components/ui-effects/HeroVideoDialog/en.json";
import type iconCloudEn from "@/components/ui-effects/IconCloud/en.json";
import type landing1En from "@/components/pages-marketing/landing-1/en.json";
import type layoutTextFlipEn from "@/components/ui-effects/LayoutTextFlip/en.json";
import type localeSwitcherEn from "@/components/layouts/_shared/LocaleSwitcher/en.json";
import type login1En from "@/components/pages-auth/login-1/en.json";
import type loginFormEn from "@/components/sections-auth/LoginForm/en.json";
import type loginPageEn from "@/components/sections-auth/Login/en.json";
import type navActionsEn from "@/components/layouts/DashboardLayout/nav/NavActions/en.json";
import type navDocumentsEn from "@/components/layouts/DashboardLayout/nav/NavDocuments/en.json";
import type navFavoritesEn from "@/components/layouts/DashboardLayout/nav/NavFavorites/en.json";
import type navMainEn from "@/components/layouts/DashboardLayout/nav/NavMain/en.json";
import type navProjectsEn from "@/components/layouts/DashboardLayout/nav/NavProjects/en.json";
import type navUserEn from "@/components/layouts/DashboardLayout/nav/NavUser/en.json";
import type navWorkspacesEn from "@/components/layouts/DashboardLayout/nav/NavWorkspaces/en.json";
import type notFound1En from "@/components/pages-error/not-found-1/en.json";
import type pixelatedCanvasEn from "@/components/ui-effects/PixelatedCanvas/en.json";
import type pricing1En from "@/components/sections-marketing-pricing/pricing-1/en.json";
import type pricingComparatorEn from "@/components/sections-marketing-pricing/pricing-comparator/en.json";
import type searchFormEn from "@/components/layouts/DashboardLayout/widgets/SearchForm/en.json";
import type sectionCardsEn from "@/components/sections-app-dashboard/SectionCards/en.json";
import type settingsDialogEn from "@/components/sections-app-settings/SettingsDialog/en.json";
import type sidebarEn from "@/components/layouts/SidebarLayout/en.json";
import type sidebarLeftEn from "@/components/layouts/DashboardLayout/sidebars/SidebarLeft/en.json";
import type sidebarOptInFormEn from "@/components/layouts/DashboardLayout/widgets/SidebarOptInForm/en.json";
import type sidebarRightEn from "@/components/layouts/DashboardLayout/sidebars/SidebarRight/en.json";
import type sidebarTriggerEn from "@/components/ui-effects/SidebarTrigger/en.json";
import type signup1En from "@/components/pages-auth/signup-1/en.json";
import type signupFormEn from "@/components/sections-auth/SignupForm/en.json";
import type signupPageEn from "@/components/sections-auth/SignUp/en.json";
import type siteFooterEn from "@/components/layouts/DefaultLayout/SiteFooter/en.json";
import type siteHeaderEn from "@/components/layouts/DefaultLayout/SiteHeader/en.json";
import type skipLinkEn from "@/components/layouts/_shared/SkipLink/en.json";
import type stats1En from "@/components/sections-marketing-stats/stats-1/en.json";
import type stats2En from "@/components/sections-marketing-stats/stats-2/en.json";
import type stats3En from "@/components/sections-marketing-stats/stats-3/en.json";
import type stats4En from "@/components/sections-marketing-stats/stats-4/en.json";
import type team1En from "@/components/sections-marketing-team/team-1/en.json";
import type teamSwitcherEn from "@/components/layouts/DashboardLayout/widgets/TeamSwitcher/en.json";
import type testimonials1En from "@/components/sections-marketing-testimonials/testimonials-1/en.json";
import type themeToggleEn from "@/components/layouts/_shared/ThemeToggle/en.json";
import type tweetNotFoundEn from "@/components/ui-effects/TweetNotFound/en.json";
import type versionSwitcherEn from "@/components/layouts/DashboardLayout/widgets/VersionSwitcher/en.json";
import type webcamPixelGridEn from "@/components/ui-effects/WebcamPixelGrid/en.json";
import type worldMapEn from "@/components/ui-effects/WorldMap/en.json";

type MergedMessages = typeof globalEn & {
  pages: {
    home: typeof homeEn;
    about: typeof aboutEn;
  };
  blocks: {
    "3d-pin": typeof _3dPinEn;
    "about-1": typeof about1En;
    "animated-testimonials": typeof animatedTestimonialsEn;
    "app-sidebar": typeof appSidebarEn;
    "chart-area-axes": typeof chartAreaAxesEn;
    "chart-area-default": typeof chartAreaDefaultEn;
    "chart-area-gradient": typeof chartAreaGradientEn;
    "chart-area-icons": typeof chartAreaIconsEn;
    "chart-area-interactive": typeof chartAreaInteractiveEn;
    "chart-area-legend": typeof chartAreaLegendEn;
    "chart-area-linear": typeof chartAreaLinearEn;
    "chart-area-stacked": typeof chartAreaStackedEn;
    "chart-area-stacked-expand": typeof chartAreaStackedExpandEn;
    "chart-area-step": typeof chartAreaStepEn;
    "chart-bar-active": typeof chartBarActiveEn;
    "chart-bar-default": typeof chartBarDefaultEn;
    "chart-bar-horizontal": typeof chartBarHorizontalEn;
    "chart-bar-interactive": typeof chartBarInteractiveEn;
    "chart-bar-label-custom": typeof chartBarLabelCustomEn;
    "command-palette": typeof commandPaletteEn;
    "contact-1": typeof contact1En;
    "content-1": typeof content1En;
    "content-2": typeof content2En;
    "content-3": typeof content3En;
    "content-4": typeof content4En;
    "content-5": typeof content5En;
    "content-6": typeof content6En;
    "content-7": typeof content7En;
    "cta-1": typeof cta1En;
    "dashboard-1": typeof dashboard1En;
    "dashboard-header": typeof dashboardHeaderEn;
    "data-table": typeof dataTableEn;
    "dither-shader": typeof ditherShaderEn;
    "error-1": typeof error1En;
    "faq-1": typeof faq1En;
    "faq-2": typeof faq2En;
    "faq-3": typeof faq3En;
    "faq-4": typeof faq4En;
    "features-1": typeof features1En;
    "features-10": typeof features10En;
    "features-11": typeof features11En;
    "features-12": typeof features12En;
    "features-2": typeof features2En;
    "features-3": typeof features3En;
    "features-4": typeof features4En;
    "features-5": typeof features5En;
    "features-6": typeof features6En;
    "features-7": typeof features7En;
    "features-8": typeof features8En;
    "features-9": typeof features9En;
    "footer-1": typeof footer1En;
    "forgot-password": typeof forgotPasswordEn;
    "forgot-password-1": typeof forgotPassword1En;
    "hero-video-dialog": typeof heroVideoDialogEn;
    "icon-cloud": typeof iconCloudEn;
    "landing-1": typeof landing1En;
    "layout-text-flip": typeof layoutTextFlipEn;
    "locale-switcher": typeof localeSwitcherEn;
    "login-1": typeof login1En;
    "login-form": typeof loginFormEn;
    "login-page": typeof loginPageEn;
    "nav-actions": typeof navActionsEn;
    "nav-documents": typeof navDocumentsEn;
    "nav-favorites": typeof navFavoritesEn;
    "nav-main": typeof navMainEn;
    "nav-projects": typeof navProjectsEn;
    "nav-user": typeof navUserEn;
    "nav-workspaces": typeof navWorkspacesEn;
    "not-found-1": typeof notFound1En;
    "pixelated-canvas": typeof pixelatedCanvasEn;
    "pricing-1": typeof pricing1En;
    "pricing-comparator": typeof pricingComparatorEn;
    "search-form": typeof searchFormEn;
    "section-cards": typeof sectionCardsEn;
    "settings-dialog": typeof settingsDialogEn;
    "sidebar": typeof sidebarEn;
    "sidebar-left": typeof sidebarLeftEn;
    "sidebar-opt-in-form": typeof sidebarOptInFormEn;
    "sidebar-right": typeof sidebarRightEn;
    "sidebar-trigger": typeof sidebarTriggerEn;
    "signup-1": typeof signup1En;
    "signup-form": typeof signupFormEn;
    "signup-page": typeof signupPageEn;
    "site-footer": typeof siteFooterEn;
    "site-header": typeof siteHeaderEn;
    "skip-link": typeof skipLinkEn;
    "stats-1": typeof stats1En;
    "stats-2": typeof stats2En;
    "stats-3": typeof stats3En;
    "stats-4": typeof stats4En;
    "team-1": typeof team1En;
    "team-switcher": typeof teamSwitcherEn;
    "testimonials-1": typeof testimonials1En;
    "theme-toggle": typeof themeToggleEn;
    "tweet-not-found": typeof tweetNotFoundEn;
    "version-switcher": typeof versionSwitcherEn;
    "webcam-pixel-grid": typeof webcamPixelGridEn;
    "world-map": typeof worldMapEn;
  };
};

/** Recursive dotted path extractor — depth-limited so TypeScript doesn't blow up. */
type DotPath<T, Depth extends number[] = []> = Depth["length"] extends 6
  ? never
  : T extends Record<string, unknown>
    ? {
        [K in keyof T & string]:
          | K
          | `${K}.${DotPath<T[K], [...Depth, 1]>}`;
      }[keyof T & string]
    : never;

/** Every dotted translation key the merged tree exposes — fed to `titleKey`, `labelKey`, … */
export type MessageKey = DotPath<MergedMessages>;
