// GENERATED by `scripts/version.mjs` (runs inside build:cf). Do not edit.
// Committed placeholder — real values are stamped at build time. `commit` is the
// version-check baseline (compared against `/api/version`).
export const buildInfo = {
  version: "0.0.0",
  branch: "local",
  commit: "dev",
  buildTime: "",
} as const;
