// AUTO-GENERATED by scripts/generate-routes.mjs
// DO NOT EDIT — run `pnpm gen:routes` to regenerate. Drift caught by `pnpm verify:routes`.

/**
 * Auto-derived route union. Source of truth: each route's
 * `src/app/[locale]/<seg>/page.config.ts`.
 *
 * Hand-maintained intentionally elsewhere:
 *   - DynamicAppPathname (dynamic segments like "/blog/[slug]")
 *   - AppPathname (static + dynamic union)
 *
 * Adding a static route: drop a `page.config.ts` and run `pnpm gen:routes`.
 */

export type StaticAppPathname =
  | "/"
  | "/about"
  | "/dashboard"
  | "/forgot-password"
  | "/login"
  | "/signup";

export type DynamicAppPathname = never;

export type AppPathname = StaticAppPathname | DynamicAppPathname;
