// AUTO-GENERATED by scripts/generate-routes.mjs
// DO NOT EDIT — run `pnpm gen:routes` to regenerate. Drift caught by `pnpm verify:routes`.

import { expandSlug } from "./expand-slug";
import homePage from "@/app/[locale]/page.config";

export const PAGES = [homePage] as const;

export const PATHNAMES = {
  "/": expandSlug(homePage.slugs),
} as const;

export { homePage };
