/// <reference types="expo/types" />

// NOTE: This file is auto-generated by Expo (referenced from tsconfig `include`).
// It brings in Expo's ambient types — including the typed `process.env.EXPO_PUBLIC_*`
// surface that `lib/agent.ts` reads for the shared-agent base URL + token.
