#!/usr/bin/env node
/**
 * Auto-generate the route registry from each route's `page.config.ts`.
 *
 * Walks `src/app/[locale]/**` for `page.config.ts` files and emits two
 * committed files:
 *
 *   - src/config/routes.types.ts          : `StaticAppPathname` literal
 *                                           union (no imports — breaks the
 *                                           circular dep with section schemas)
 *   - src/config/pages/registry.generated.ts : import list + PAGES array
 *
 * The hand-written `src/config/pages/index.ts` consumes
 * `registry.generated.ts` to build PATHNAMES (preserves per-locale custom
 * slugs from each `page.config.ts`).
 *
 * Drift is caught by `pnpm verify:routes` (regen + diff).
 *
 * Per-locale slugs (`slugs: { en: "/about", fr: "/a-propos" }`) are
 * preserved verbatim — the codegen reads each config's `slugs` object via
 * regex and stores it on the imported PageConfig, which downstream code
 * spreads into the PATHNAMES table.
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = process.cwd();
const APP_LOCALE_DIR = join(ROOT, "src/app/[locale]");
const ROUTES_TYPES_OUT = join(ROOT, "src/config/routes.types.ts");
const REGISTRY_OUT = join(ROOT, "src/config/pages/registry.generated.ts");

const HEADER = `// AUTO-GENERATED by scripts/generate-routes.mjs
// DO NOT EDIT — run \`pnpm gen:routes\` to regenerate. Drift caught by \`pnpm verify:routes\`.
`;

function walk(dir, files = []) {
  for (const e of readdirSync(dir)) {
    const f = join(dir, e);
    const st = statSync(f);
    if (st.isDirectory()) {
      walk(f, files);
    } else if (f.endsWith("/page.config.ts")) {
      files.push(f);
    }
  }
  return files;
}

const KEY_RE = /key:\s*"([^"]+)"/;
const ID_RE = /id:\s*"([^"]+)"/;

function parseConfig(absPath) {
  const src = readFileSync(absPath, "utf8");
  const keyMatch = src.match(KEY_RE);
  const idMatch = src.match(ID_RE);
  if (!keyMatch || !idMatch) {
    throw new Error(`[gen:routes] missing key/id in ${relative(ROOT, absPath)}`);
  }
  return { key: keyMatch[1], id: idMatch[1] };
}

const configs = walk(APP_LOCALE_DIR)
  .map((file) => ({ file, ...parseConfig(file) }))
  // Sort root ("/") first, then alphabetically by key — keeps PATHNAMES
  // ordering stable across regen.
  .sort((a, b) => {
    if (a.key === "/") return -1;
    if (b.key === "/") return 1;
    return a.key.localeCompare(b.key);
  });

if (configs.length === 0) {
  console.warn("! no page.config.ts files found under src/app/[locale]/");
  process.exit(1);
}

// ── routes.types.ts — literal union, NO imports ──────────────────────
// Section schemas import StaticAppPathname for href fields. If we
// imported page.configs here, schemas → page.configs → schemas would
// cycle. The literal union breaks the cycle.
const literals = configs.map((c) => `  | "${c.key}"`).join("\n");

const routesTypesContent = `${HEADER}
/**
 * Auto-derived route union. Source of truth: each route's
 * \`src/app/[locale]/<seg>/page.config.ts\`.
 *
 * Hand-maintained intentionally elsewhere:
 *   - DynamicAppPathname (dynamic segments like "/blog/[slug]")
 *   - AppPathname (static + dynamic union)
 *
 * Adding a static route: drop a \`page.config.ts\` and run \`pnpm gen:routes\`.
 */

export type StaticAppPathname =
${literals};

export type DynamicAppPathname = never;

export type AppPathname = StaticAppPathname | DynamicAppPathname;
`;

writeFileSync(ROUTES_TYPES_OUT, routesTypesContent);

// ── pages/registry.generated.ts — imports + PAGES array ──────────────
function importVarName(id) {
  // "forgot-password" → "forgotPasswordPage"
  return id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()) + "Page";
}

const imports = configs
  .map((c) => {
    const importPath =
      "@/" + relative(join(ROOT, "src"), c.file).replace(/\\/g, "/").replace(/\.ts$/, "");
    return `import ${importVarName(c.id)} from "${importPath}";`;
  })
  .join("\n");

const pagesArray = configs.map((c) => `  ${importVarName(c.id)},`).join("\n");

// PATHNAMES emitted with literal keys — preserves per-locale slugs from
// each `page.config.ts` (the `slugs` field is read at runtime via
// expandSlug, so `{ en: "/about", fr: "/a-propos" }` flows through).
const pathnamesEntries = configs
  .map((c) => `  "${c.key}": expandSlug(${importVarName(c.id)}.slugs),`)
  .join("\n");

const reExports = configs.map((c) => `  ${importVarName(c.id)},`).join("\n");

const registryContent = `${HEADER}
import { expandSlug } from "./expand-slug";
${imports}

export const PAGES = [
${pagesArray}
] as const;

export const PATHNAMES = {
${pathnamesEntries}
} as const;

export {
${reExports}
};
`;

writeFileSync(REGISTRY_OUT, registryContent);

// Format the generated files so `pnpm verify`'s format:check stays clean.
spawnSync(
  "pnpm",
  [
    "exec",
    "prettier",
    "--write",
    "--log-level",
    "silent",
    ROUTES_TYPES_OUT,
    REGISTRY_OUT,
  ],
  { stdio: "inherit" },
);

console.log(`✓ wrote ${configs.length} routes`);
console.log(`  - ${relative(ROOT, ROUTES_TYPES_OUT)}`);
console.log(`  - ${relative(ROOT, REGISTRY_OUT)}`);
