// Stamp src/lib/build-info.ts with version + git sha + build time. Runs inside
// `build:cf`, so every deployed Worker carries its provenance — the version-check
// polls `/api/version` and compares against this bundle's baked `commit`. The
// committed file holds dev placeholders.

import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const git = (cmd, fallback) => {
  try {
    return execSync(cmd, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return fallback;
  }
};

const version = JSON.parse(readFileSync("package.json", "utf8")).version ?? "0.0.0";
const branch = git("git rev-parse --abbrev-ref HEAD", "unknown");
const commit = git("git rev-parse --short HEAD", "unknown");
const buildTime = new Date().toISOString();

writeFileSync(
  "src/lib/build-info.ts",
  `// GENERATED by \`scripts/version.mjs\` (runs inside build:cf). Do not edit.
export const buildInfo = {
  version: "${version}",
  branch: "${branch}",
  commit: "${commit}",
  buildTime: "${buildTime}",
} as const;
`,
);

console.log(`build-info: ${version} (${branch}@${commit})`);
